//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mini139_res.rc
//
#define IDB_TALK_ACTION                 102
#define IDB_TALK_EMOTION1               103
#define IDB_TALK_EMOTION2               104
#define IDB_TALK_EMOTION3               105
#define IDB_TALK_EMOTION4               106
#define IDB_CHECK                       108
#define IDB_UNCHECK                     109
#define IDB_CLOSE_P2PFOLDER_NORMAL      110
#define IDB_TALK_LINKRES                111
#define IDB_BITMAP1                     112
#define IDB_LINK_RES                    112
#define IDB_MIN_DOWN                    115
#define IDB_DLG_CAPTION_R               117
#define IDB_DLG_CAPTION_L               118
#define IDB_DLG_CAPTION_M               119
#define IDB_IM_BTN_DISABLE              120
#define IDB_PICTURE_DLG_TOOL            129
#define IDB_PICTURE_FRAME               130
#define IDI_SEL_PIC                     131
#define IDB_ARTICLE                     131
#define IDB_HINT_FLAG                   132
#define IDI_ICON_UP                     134
#define IDB_MAIN_MENU_ICON              134
#define IDI_ICON_DOWN                   135
#define IDB_MY_PIC                      135
#define IDB_MY_ARTICLE                  137
#define IDB_BIGHEAD                     138
#define IDB_IM_SACAPTION                139
#define IDB_UPLOAD_PIC                  140
#define IDB_WEBINFO                     141
#define IDB_TOP_DOWN                    142
#define IDB_TOP_HOT                     143
#define IDB_TOP_NORMAIL                 144
#define IDB_UPDOWN_NORMAL               145
#define IDB_UPDOWN_HOT                  146
#define IDB_PICTURE_FLAG                151
#define IDR_HTML1                       152
#define IDB_MIN_HOT                     156
#define IDB_MIN_NORMAL                  157
#define IDB_CONTACT_OUTLOOK             158
#define IDB_CONTACT_MINI                159
#define IDB_USERGUIDE_DLG               160
#define IDB_FILETRANS_TABBTN            161
#define IDB_FAMILY_BAR_OPEN             168
#define IDB_FAMILY_BAR_HOVER            169
#define IDB_FAMILY_BAR_NORMAL           170
#define IDB_FAMILY_GROUP_STATUS         171
#define IDB_DEFAULT_ADV                 173
#define IDB_NO_IMAGE                    184
#define IDB_MAINDLG_CAPTION             191
#define IDB_PICTURE_BROAD_CAPTION       191
#define IDB_PICTURE_BROAD_SCROLL_DLG    192
#define IDB_PICTURE_BROAD_SCROLL_DLG_NORMAL 192
#define IDB_BITMAP_TEST                 194
#define IDB_PICTURE_BROAD_MENU          194
#define IDB_PICTURE_BROAD_MENU_NORMAL   194
#define IDB_ARTS_NEW                    195
#define IDB_ARTS_POST                   196
#define IDB_ARTS_SAVE                   197
#define IDB_ARTS_OPEN                   198
#define IDB_PICTURE_BROAD_MIN           199
#define IDB_PICTURE_BROAD_MIN_NORMAL    199
#define IDB_ARTICLES_DEL                200
#define IDB_PICTURE_BROAD_BUTTON_UP_NORMAL 201
#define IDB_PICTURE_BROAD_BUTTON_NORMAL 201
#define IDB_BITMAP_RIGHT2               202
#define IDB_BITMAP_RIGHT                203
#define IDB_BITMAP_LEFT                 204
#define IDB_PICTURE_BROAD_BUTTON_HOT    205
#define IDB_PICTURE_BROAD_BUTTON_UP_HOT 205
#define IDB_TOOL_BLOG                   206
#define IDB_PICTURE_BROAD_BUTTON_CLICK  207
#define IDB_PICTURE_BROAD_BUTTON_UP_CLICK 207
#define IDB_PICTURE_BROAD_BUTTON_DOWN_NORMAL 208
#define IDB_PICTURE_BROAD_BUTTON_DOWN_HOT 209
#define IDB_PICTURE_BROAD_BUTTON_DOWN_CLICK 210
#define IDB_PICTURE_BROAD_MENU_HOT      211
#define IDB_FLAG_LOGIN                  212
#define IDB_PICTURE_BROAD_MENU_CLICK    213
#define IDB_BTN_STATUS_NORMAL           214
#define IDB_BTN_STATUS_HOVER            215
#define IDB_BTN_STATUS_DOWN             216
#define IDB_MAIN_TITLE_BACK             217
#define IDB_PICTURE_BROAD_MIN_HOT       218
#define IDB_MAIN_TOOLBTNBK_MID          219
#define IDB_PICTURE_BROAD_MIN_CLICK     220
#define IDB_PICTURE_BROAD_SCROLL_DLG_HOT 221
#define IDB_BITMAP5                     222
#define IDB_PICTURE_BROAD_SCROLL_DLG_CLICK 222
#define IDB_TAB_NORMAL0                 223
#define IDB_TAB_SEL                     224
#define IDB_BTN_GOLD                    225
#define IDB_BTN_HOME                    226
#define IDI_PICTURE_BROADCAST_          226
#define IDB_BTN_MSG                     227
#define IDI_                            230
#define IDI_PICTURE_BROADCAST_TRAY      230
#define IDB_BTN_SEARCH                  232
#define IDB_FRIEND_HOT                  233
#define IDB_UPPIC                       234
#define IDB_WRITEBLOG                   235
#define IDB_LOGINING_TITLE              236
#define IDB_LOGINING_PAUSE              237
#define IDB_BTN1_DOWN                   238
#define IDB_BTN1_DISABLE                239
#define IDB_BTN1_HOT                    240
#define IDB_BTN1_NORMAL                 241
#define IDB_RECENT_NORMAL               242
#define IDB_FRIEND_NORMAL               243
#define IDB_TALK_TITLE_BACK             244
#define IDB_BTN_CARD                    245
#define IDB_GROUPLIST_BUTTON            247
#define IDB_BTN_VISIT                   248
#define IDB_GROUP_HOT                   249
#define IDB_P2PTOOLFONT_BACK            250
#define IDB_TALK_TEXTCOLOR              251
#define IDB_GROUP_NORMAL                254
#define IDB_RECENT_HOT                  255
#define IDB_IM_STATUS35                 256
#define IDB_BTN_WEBSMS                  257
#define IDB_BTN_ADDFRIEND               258
#define IDB_IM_BTN_NORMAL               259
#define IDB_IM_BTN_HOVER                260
#define IDB_TALK_MAGICFACE              262
#define IDB_BTNLOGIN_NORMAL             263
#define IDB_IM_SEARCHFRIEND             264
#define IDB_BTNLOGIN_HOT                265
#define IDB_BTNLOGIN_DOWN               266
#define IDB_BITMAP_SYS_SET_HOVER        267
#define IDB_BITMAP_SYS_SET_NORMAL       268
#define IDB_IM_MOBILE                   269
#define IDB_BITMAP_SYS_SET_PRESSED      270
#define IDB_BITMAP_SYS_SET_DISABLE      271
#define IDB_BITMAP_SYS_MSG_HOVER        272
#define IDB_BITMAP_SYS_MSG_NORMAL       273
#define IDB_BITMAP_SYS_MSG_PRESSED      274
#define IDB_BITMAP_SYS_MSG_DISABLE      275
#define IDB_BITMAP_SYS_MENU_HOVER       276
#define IDB_BITMAP_SYS_MENU_NORMAL      277
#define IDB_BITMAP_SYS_MENU_DISABLE     279
#define IDB_BITMAP_ADD_MEMBER           280
#define IDB_BITMAP_SYS_ADD_NORMAL       281
#define IDR_GIF_LOGIN                   282
#define IDB_BITMAP_SYS_ADD_PRESSED      282
#define IDB_BTN_COLOR_DOWN              283
#define IDB_BTN_BOLD_NORMAL             284
#define IDB_BTN_BOLD_SEL                285
#define IDB_BTN_BOLD_DOWN               286
#define IDB_BTN_COLOR_NORMAL            287
#define IDB_BTN_ITALIC_DOWN             288
#define IDB_BTN_ITALIC_NORMAL           289
#define IDB_BTN_ITALIC_SEL              290
#define IDB_BTN_UNDERLINE_DOWN          291
#define IDB_BTN_UNDERLINE_NORMAL        292
#define IDB_BTN_UNDERLINE_SEL           293
#define IDB_BLOG_LOGO                   295
#define IDB_LOGO_HMG                    296
#define IDB_MENU_TITLE                  297
#define IDB_BITMAP_SYS_ADD_DISABLE      298
#define IDB_IM_FOLDER                   300
#define IDB_IM_FOLDER_EXPAND            301
#define IDB_IM_FOLDER_CLOSE             302
#define IDB_FLOOR_DOWN                  303
#define IDB_FLOOR_HOT                   304
#define IDB_FLOOR_NORMAL                305
#define IDB_IM_STATUS20                 306
#define IDB_IM_STATUS40                 307
#define IDB_BITMAP_CHAT_HOVER           310
#define IDB_BITMAP_CHAT_NORMAL          311
#define IDB_BITMAP_CHAT_PRESSED         312
#define IDB_BITMAP_SEARCH_MEMBER        313
#define IDB_BTN_EXPORT                  314
#define IDB_BTN_REFRESH                 315
#define IDB_MSG_LIST                    316
#define IDB_BTN_LAST                    317
#define IDB_BTN_NEXT                    318
#define IDB_BTN_PREV                    319
#define IDB_BTN_FIRST                   320
#define IDB_SEARCH                      321
#define IDB_BTN_PREV_DISABLE            322
#define IDB_BTN_LAST_DISABLE            323
#define IDB_BTN_NEXT_DISABLE            324
#define IDB_BTN_FIRST_DISABLE           325
#define IDB_CLUSTER                     326
#define IDB_BITMAP_SYS_MENU_PRESSED     327
#define IDB_BITMAP_SYS_ADD_HOVER        329
#define IDB_HINT_CLOSE_NORMAL           331
#define IDB_HINT_CLOSE_HOVER            332
#define IDB_HINT_DLG                    333
#define IDB_IM_BTN_DOWN                 336
#define IDB_CLUSTER_CREATOR             337
#define IDB_FRIEND_BLOG                 338
#define IDB_HINT_ICON                   339
#define IDB_TAB_NORMAL                  340
#define IDB_RIGHT_MENU                  341
#define IDB_BLOG_POST                   342
#define IDB_BLOG_RESET                  343
#define IDB_WEATHER                     344
#define IDB_ARROW_DOWN                  345
#define IDB_ARROW_UP                    346
#define IDB_BITMAP_BIG2                 347
#define IDB_IM_HEAD40                   349
#define IDB_BITMAP3                     350
#define IDB_BITMAP_HISTORY_RECORD       350
#define IDB_GROUP_STATUS30              351
#define IDB_GROUP_STATUS35              352
#define IDB_GROUP_STATUS47              353
#define IDB_GROUP_STATUS88              354
#define IDB_IM_STATUS100                355
#define IDB_BTN_BIGHEAD                 356
#define IDB_BTN_ADD                     357
#define IDB_BTN_CFG                     358
#define IDB_BTN_DEL                     359
#define IDB_BTN_MODIFY                  360
#define IDB_CHANEL_IM                   361
#define IDB_CHANEL_SHOP                 362
#define IDB_CHANEL_TAG                  363
#define IDB_CHANEL_FAMILY               364
#define IDB_CHANEL_MINI139              365
#define IDB_CHANEL_ALBUM                366
#define IDB_CHANEL_MOBILE               367
#define IDB_SCREEN_CUT_TIP              368
#define IDB_CLUSTER_ADMIN               369
#define IDB_IM_STATUS24                 370
#define IDB_IM_STATUS30                 371
#define IDB_WIN2K_ICON                  372
#define IDB_IM_STATUS47                 373
#define IDB_IM_STATUS52                 374
#define IDB_IM_STATUS88                 375
#define IDB_IM_SCROLLBAR                376
#define IDB_MAINICON                    377
#define IDB_IM_STATUS16                 378
#define IDB_BITMAP6                     378
#define IDB_BITMAP_CLEAR_CONTENTS       378
#define IDB_WINXP_ICON                  379
#define IDB_MSG_LINE                    380
#define IDB_BITMAP_LEFT_DISABLE         381
#define IDB_STATUS_FOOT40               382
#define IDB_STATUS_FOOT20               383
#define IDB_IM_HEAD20                   384
#define IDB_BITMAP_LEFT_HOVER           386
#define IDB_BITMAP_LEFT_NORMAL          387
#define IDB_BITMAP_LEFT_PRESSED         388
#define IDB_EMOTION2                    389
#define IDB_BITMAP_BIG                  390
#define IDR_MAINFRAME1                  390
#define IDB_BITMAP_LEFT2                391
#define IDI_UPD_PIC                     391
#define IDB_IM_CLUSTER                  392
#define IDI_FRIEND_PIC_ENTRY            392
#define IDB_LOGIN_PASSHINT              393
#define IDI_FRIEND_LOG_ENTRY            393
#define IDI_FRIEND_LOG_ENTRY1           394
#define IDI_BIGHEAD                     394
#define IDB_BITMAP_LEFTEST_DISABLE      394
#define IDI_MY_PIC                      395
#define IDB_BITMAP_LEFTEST_HOVER        395
#define IDB_CHANEL_BODCAST              396
#define IDI_MY_ARTICLE                  396
#define IDI_MY_ARTICLE1                 397
#define IDI_WRITEBLOG                   397
#define IDB_BITMAP_LEFTEST_NORMAL       397
#define IDI_139NOTE                     398
#define IDB_BITMAP_LEFTEST_PRESSED      398
#define IDB_BITMAP_BACK_DISABLE         399
#define IDB_BITMAP_BACK_HOVER           400
#define IDB_CLUSTER_ACCEPTMSG           401
#define IDB_CLUSTER_REFUSE              402
#define IDB_BITMAP_BACK_NORMAL          403
#define IDB_BITMAP_BACK_PRESSED         404
#define IDB_BITMAP_BACKEST_DISABLE      405
#define IDB_BMP_LEVEL                   406
#define IDB_BITMAP_BACKEST_HOVER        407
#define IDB_VIP_CLUSTER                 408
#define IDB_ICON_CVIP                   409
#define IDB_ICON_FAMILY16               410
#define IDB_SHOW_P2PFOLDER_NORMAL       411
#define IDB_CLOSE_P2PFOLDER_HOVER       412
#define IDB_SHOW_P2PFOLDER_HOVER        413
#define IDB_ICON_FAMILY40               414
#define IDB_BITMAP_BACKEST_NORMAL       416
#define IDB_BITMAP_BACKEST_PRESSED      417
#define IDB_BITMAP_FRIEND_NORMAL        419
#define IDB_BITMAP_FRIEND_PRESSED       420
#define IDB_FRIEND_LOG                  427
#define IDB_FRIEND_PIC                  428
#define IDB_MAIN_MENU                   429
#define IDB_FOCUSON                     430
#define IDB_WEBINFO2                    431
#define IDB_FOCUSOFF                    431
#define IDB_WEBPIC                      432
#define IDB_WEBARTICLE                  433
#define IDB_STAR                        434
#define IDB_BTN_ZONE                    435
#define IDB_PICTURE_ERROR               436
#define IDB_BITMAP26                    437
#define IDB_BITMAP27                    438
#define IDB_CONTACT_INVITE              439
#define IDB_FRIEND_MAILINVITE           440
#define IDB_CONTACT_OUTLOOK1            441
#define IDB_CONTACT_SENDMAIL            442
#define IDB_MAILINVITE                  443
#define IDB_BTN_MODIFY1                 444
#define IDB_BITMAP28                    444
#define IDB_BTN_MINILINK                445
#define IDB_FILETRANS_TABBTN1           446
#define IDB_FILETRANS_BTN               446
#define IDB_FAMILY_HEAD                 447
#define IDB_FAMILY_GROUPTOOL            448
#define IDB_BTN_INVITE1                 449
#define IDB_BTN_SENDFILE                449
#define IDB_BITMAP29                    449
#define IDB_BTN_GOLD1                   450
#define IDB_BTN_139NOTE2                450
#define IDB_BTN_139NOTE                 451
#define IDB_IM_COMBO_BUTTON             452
#define IDB_ARTICLE1                    453
#define IDB_NOTE_BTN1                   453
#define IDB_NOTE_BTN2                   454
#define IDB_TABPAGE_FRIENDS             455
#define IDB_TABPAGE_WOKU                456
#define IDB_TABPAGE_FUN                 457
#define IDB_HEADER_BACK                 458
#define IDB_FAMILY_HEAD1                459
#define IDB_IMTAB_HOT                   460
#define IDB_IMTAB_NORMAL                461
#define IDB_BTN_GOLD2                   462
#define IDB_BTN_LEVEL                   462
#define IDB_TAB_NORMAL1                 463
#define IDB_TAB_NORMAL2                 464
#define IDB_BITMAP_CFG_HOVER            465
#define IDB_BITMAP_CFG_NORMAL           466
#define IDB_BITMAP7                     467
#define IDB_BITMAP_CFG_PRESSED          467
#define IDB_BMP_DEL_HOVER               468
#define IDB_BMP_DEL_NORMAL              469
#define IDB_BITMAP8                     470
#define IDB_BMP_DEL_PRESSED             470
#define IDB_BMP_ARROW_RIGHT             471
#define IDB_BITMAP_                     472
#define IDB_BMP_HOTKEY_NORMAL           473
#define IDB_BITMAP9                     474
#define IDB_BMP_HOTKEY_PRESSED          474
#define IDB_BITMAP2                     475
#define IDB_BMP_HOTKEY_HOVER            475
#define IDB_PNG_CHOOSE                  476
#define IDB_PNG_SENDBTN_LEFT_HOVER      477
#define IDB_PNG_SENDBTN_LEFT_NORMAL     478
#define IDB_PNG_SENDBTN_LEFT_PRESSED    479
#define IDB_PNG_SENDBTN_RIGHT_NORMAL    480
#define IDB_PNG_SENDBTN_RIGHT_HOVER     481
#define IDB_PNG_SENDBTN_RIGHT_PRESSED   482
#define IDB_PNG_SCREEN_PREESED          483
#define IDB_PNG_SCREEN_OPTION_PRESSED   484
#define IDB_PNG_SCREEN_OPTION_HOVER     485
#define IDB_PNG_SCREEN_NORM             486
#define IDB_PNG_SCREEN_HOVER            487
#define IDB_PNG_SCREEN_OPTION_NORM      488
#define IDB_BMP_GRAY_BTN_HOVER_L        489
#define IDB_BMP_GRAY_BTN_NORMAL_L       490
#define IDB_BMP_GRAY_BTN_PRESSED_L      491
#define IDB_BMP_SENIOR_BTN_HOVER        492
#define IDB_BMP_SENIOR_BTN_NORMAL       493
#define IDB_BMP_SENIOR_BTN_PRESSED      494
#define IDC_NODROP                      507
#define IDC_DROP                        508
#define IDB_ZONE_SETTING                509
#define IDB_ZONE_BIGHEAD                510
#define IDB_ZONE_MYPICTURE              511
#define IDB_ZONE_UPLOAD_PICTURE         512
#define IDB_ZONE_MYARTICLE              513
#define IDB_ZONE_WRITE_ARTICLE          514
#define IDB_ZONE_ACCOUNT                515
#define IDB_ZONE_SHOP                   516
#define IDB_ZONE_ICON1                  517
#define IDB_ZONE_CHANGEHEAD             518
#define IDB_BTN_CREATEFAMILY            519
#define IDB_ZONE_MYPICTURE1             520
#define IDB_ZONE_MYHOME                 520
#define IDB_VOICE_THUM                  555
#define IDB_HORN                        556
#define IDB_MICROPHONE                  557
#define IDB_VEDIO_ON                    558
#define IDB_VEDIO_OFF                   559
#define IDB_VEDIO_SNATCH                560
#define IDB_VEDIO                       561
#define IDB_VEDIO_SMALL                 561
#define IDB_FRIEND_MOBILE               563
#define IDB_FRIEND_VEDIO                564
#define IDB_HINT_VEDIO                  565
#define IDB_ARTS_INSERT_LOCAL_IMAGE     566
#define IDB_ARTS_INSERT_INTERNET_IMAGE  567
#define IDB_ARTS_INSERT_LINK            568
#define IDB_ARTICLE_SEL                 569
#define IDB_ARTS_DEL_N                  570
#define IDB_ARTS_DEL_H                  571
#define IDB_ARTS_DEL_D                  572
#define IDB_ARTS_ITEM                   573
#define IDB_ARTS_INSERT_WOKU_IMAGE      574
#define IDB_ZONE_MEDIA                  575
#define IDB_BTN_MEDIA                   576
#define IDB_BTN_VEDIO                   577
#define IDB_BTN_VEDIO_CLOSE_D           581
#define IDB_BTN_VEDIO_CLOSE_N           582
#define IDB_BTN_VEDIO_CLOSE_H           583
#define IDB_BTN_AUDIO_CLOSE_D           584
#define IDB_BTN_AUDIO_CLOSE_H           585
#define IDB_BTN_AUDIO_CLOSE_N           586
#define IDB_VEDIO_BIG                   587
#define IDB_HINT_FLAG2                  588
#define IDB_SMS_BTN1                    589
#define IDB_NOTE_BTN4                   590
#define IDB_SMS_BTN2                    590
#define IDB_ALBUM_MOBILE                591
#define IDB_ALBUM_DRAFT                 592
#define IDB_ALBUM_ALL                   593
#define IDB_ALBUM_ALL1                  594
#define IDB_ALBUM_CUSTOM                594
#define IDB_BTN_COLOR_SEL               595
#define IDB_CHAT_CLOSE_NORMAL           597
#define IDB_CHAT_CLOSE_HOT              598
#define IDB_CHAT_CLOSE_DOWN             599
#define IDB_CHAT_MAX_HOT                600
#define IDB_CHAT_MAX_DOWN               601
#define IDB_CHAT_MAX_NORMAL             602
#define IDB_CHAT_MIN_HOT                603
#define IDB_CHAT_MIN_DOWN               604
#define IDB_CHAT_MIN_NORMAL             605
#define IDB_BTN_AUDIO_NORMAL            606
#define IDB_BTN_AUDIO_HOT               607
#define IDB_BTN_AUDIO_DOWN              608
#define IDB_BTN_VEDIO_NORMAL            609
#define IDB_BTN_VEDIO_HOT               610
#define IDB_BTN_VEDIO_DOWN              611
#define IDB_BTN_SENDFILE_NORMAL         612
#define IDB_BTN_SENDFILE_HOT            613
#define IDB_BTN_SENDFILE_DOWN           614
#define IDB_TALK_FONT_NORMAL            615
#define IDB_TALK_FONT_HOT               616
#define IDB_TALK_FONT_DOWN              617
#define IDB_TALK_FONT_DISABLE           618
#define IDB_TALK_EMOTION_NORMAL         619
#define IDB_TALK_EMOTION_HOT            620
#define IDB_TALK_EMOTION_DOWN           621
#define IDB_TALK_EMOTION_DISABLE        622
#define IDB_TALK_SOUND_NORMAL           623
#define IDB_TALK_SOUND_HOT              624
#define IDB_TALK_SOUND_DOWN             625
#define IDB_TALK_SOUND_DISABLE          626
#define IDB_TALK_SENDPIC_NORMAL         627
#define IDB_TALK_SENDPIC_HOT            628
#define IDB_TALK_SENDPIC_DOWN           629
#define IDB_TALK_SENDPIC_DISABLE        630
#define IDB_BTN_SCREEN_COPY_NORMAL      631
#define IDB_BTN_SCREEN_COPY_HOT         632
#define IDB_BTN_SCREEN_COPY_DOWN        633
#define IDB_BTN_SCREEN_COPY_DISABLE     634
#define IDB_BTN_VIBRATION_NORMAL        635
#define IDB_BTN_VIBRATION_HOT           636
#define IDB_BTN_VIBRATION_DOWN          637
#define IDB_BTN_VIBRATION_DISABLE       638
#define IDB_BTN_SCORE_NORMAL            639
#define IDB_BTN_SCORE_HOT               640
#define IDB_BTN_SCORE_DOWN              641
#define IDB_BTN_SCORE_DISABLE           642
#define IDB_BTN_HISTORY_NORMAL          643
#define IDB_BTN_HISTORY_DOWN            644
#define IDB_HINT_CLUSTER_DLG            645
#define IDB_PNG_FONT_BOLD_DISABLE       646
#define IDB_PNG_FONT_BOLD_HOVER         647
#define IDB_PNG_FONT_BOLD_PRESSED       648
#define IDB_PNG_FONT_BOLD_NORMAL        649
#define IDB_PNG_FONT_COLOR_DISABLE      650
#define IDB_PNG_FONT_COLOR_HOVER        651
#define IDB_PNG_FONT_COLOR_PRESSED      652
#define IDB_PNG_FONT_COLOR_NORMAL       653
#define IDB_PNG_FONT_ITALICS_DISABLE    654
#define IDB_PNG_FONT_ITALICS_HOVER      655
#define IDB_PNG_FONT_ITALICS_PRESSED    656
#define IDB_PNG_FONT_ITALICS_NORMAL     657
#define IDB_PNG_FONT_UNDERLINE_DISABLE  658
#define IDB_PNG_FONT_UNDERLINE_HOVER    660
#define IDB_PNG_FONT_UNDERLINE_PRESSED  661
#define IDB_PNG_FONT_UNDERLINE_NORMAL   662

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        663
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
