copy "..\HmgSkin\FlatDateTimeCtrl.h"  "include\FlatDateTimeCtrl.h"
copy "..\HmgSkin\FlatEdit.h"  "include\FlatEdit.h"
copy "..\HmgSkin\GraphComboBox.h"  "include\GraphComboBox.h"
copy "..\HmgSkin\HmgSkinPublic.h"  "include\HmgSkinPublic.h"
copy "..\HmgSkin\HyperBtn.h"  "include\HyperBtn.h"
copy "..\HmgSkin\MenuEx.h"  "include\MenuEx.h"
copy "..\HmgSkin\PictureEx.h"  "include\PictureEx.hh"
copy "..\HmgSkin\SplitterControl.h"  "include\SplitterControl.h"
copy "..\HmgSkin\XButton.h"  "include\XButton.h"
copy "..\HmgSkin\XHeaderCtrl.h"  "include\XHeaderCtrl.h"
copy "..\HmgSkin\XListCtrl.h"  "include\XListCtrl.h"
copy "..\HmgSkin\XSkinDlg.h"  "include\XSkinDlg.h"
copy "..\HmgSkin\XSliderCtrl.h"  "include\XSliderCtrl.h"
copy "..\HmgSkin\PictureEx.h"  "include\PictureEx.h"
copy "..\HmgSkin\SkinBitmap.h"  "include\SkinBitmap.h"
pause