// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef PROTOBUF_base_2eproto__INCLUDED
#define PROTOBUF_base_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_base_2eproto();
void protobuf_AssignDesc_base_2eproto();
void protobuf_ShutdownFile_base_2eproto();


enum EuMsgPush {
  MP_NEWORDER = 1,
  MP_PAYORDER = 2,
  MP_RETURNORDER = 3,
  MP_GOODSCOMMENT = 4
};
bool EuMsgPush_IsValid(int value);
const EuMsgPush EuMsgPush_MIN = MP_NEWORDER;
const EuMsgPush EuMsgPush_MAX = MP_GOODSCOMMENT;
const int EuMsgPush_ARRAYSIZE = EuMsgPush_MAX + 1;

enum CSCmdID {
  CS_CID_MSGPUSH_IND = 40961
};
bool CSCmdID_IsValid(int value);
const CSCmdID CSCmdID_MIN = CS_CID_MSGPUSH_IND;
const CSCmdID CSCmdID_MAX = CS_CID_MSGPUSH_IND;
const int CSCmdID_ARRAYSIZE = CSCmdID_MAX + 1;

enum SSCmdID {
  SS_CID_MSG_PUSH = 61441
};
bool SSCmdID_IsValid(int value);
const SSCmdID SSCmdID_MIN = SS_CID_MSG_PUSH;
const SSCmdID SSCmdID_MAX = SS_CID_MSG_PUSH;
const int SSCmdID_ARRAYSIZE = SSCmdID_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_base_2eproto__INCLUDED
