//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IMClient.rc
//
#define IDM_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   102
#define IDD_MAIN                        103
#define IDR_RIGHT_CLICK                 104
#define IDR_LEFT_CLICK                  105
#define IDD_DIALOG_LOGIN                106
#define IDD_CLUSTER_PANEL               107
#define IDD_DIALOG_INVITE               108
#define IDD_DIALOG_INVITE_SEL           109
#define IDD_DIALOG_DOWNLOAD             110
#define IDD_DIALOG_VERSION_INFO         111
#define IDD_IMAGEPREVIEWDLG             112
#define IDD_DIALOG_ADDEMOTION           113
#define IDD_DIALOG_EMOTION_MANAGE       114
#define IDD_DIALOG_TABWND               115
#define IDR_TOOLBAR_BLOG                116
#define IDD_FLOOR_FRIEND                117
#define IDD_P2P_SENDMSG                 118
#define IDD_DIALOG_EMOTION              119
#define IDD_DIALOG_FRIENDINFO           120
#define IDR_MENU_TEMPLATE               121
#define IDD_SA_PAGE3                    122
#define IDD_SA_PAGE2                    123
#define IDD_SA_PAGE1                    124
#define IDD_SA_CONFIG                   125
#define IDD_SA_PAGE4                    126
#define IDD_DIALOG_HINT                 127
#define IDD_FRIEND_SEARCH               128
#define IDD_FS_XTREAM                   129
#define IDD_FS_RESULT                   130
#define IDD_MSG_DIALOG                  131
#define IDD_SCREEN_COPY                 132
#define IDD_SCREEN_COPY_HINT            133
#define IDD_DIALOG_USERAUTHREQ          134
#define IDD_DIALOG_USERAUTHINFO         135
#define IDD_WIZARD_CLUSTER              136
#define IDD_WIZARD_CLUSTER_PAGE1        137
#define IDD_TAB_PAGE2                   138
#define IDD_FLOOR_CLUSTER               139
#define IDD_WIZARD_CLUSTER_PAGE2        140
#define IDD_WIZARD_CLUSTER_PAGE3        141
#define IDD_CLUSTER_SENDMSG             142
#define IDD_FS_CLUSTER                  143
#define IDD_FS_SELECT                   144
#define IDD_DIALOG_CSETTING             145
#define IDD_P2PUSER_INFO                146
#define IDD_P2PUSER_LIST                147
#define IDD_FLOOR_ADDBOOK               148
#define IDD_DIALOG_ADD_ADDRESS          149
#define IDD_DIALOG_PROGRESS             150
#define IDD_DIALOG_ADD_ADDRESS_CROLL_PART 151
#define IDD_DIALOG_MYSHOW               152
#define IDD_DIALOG_SYSMSG               153
#define IDD_DIALOG_ABOUTBOX             154
#define IDD_HINT_PASSDLG                155
#define IDD_SAPAGE_HOTKEY               156
#define IDR_SENDMSG_HOTKEY              157
#define IDD_SELECT_GROUP                158
#define IDD_SAPAGE_BASICSET             159
#define IDR_MAINFRAME_HOTKEY            160
#define IDD_DIALOG_CLUSTERINFO          161
#define IDD_MODF_COMMNAME               162
#define IDD_SENDMSG_ACTION              163
#define IDD_MSGBOX                      164
#define IDD_LINKRES                     165
#define IDD_DIALOG_FRIENDPICTURE_ENTRY  166
#define IDD_DIALOG_SHOW_HELP            167
#define IDD_DIALOG_FRIENDLOG_ENTRY      168
#define IDD_DIALOG_INSERTLINK           169
#define IDR_MAIN_MENU                   170
#define IDR_ACC_FINDFRIEND              171
#define IDD_DIALOG_TEST_WEBPIC          172
#define IDD_SA_PAGE5                    173
#define IDD_SA_CLUSTERMSGSET            174
#define IDD_CHANGE_ACCOUNT              175
#define IDD_DIALOG_SMS                  176
#define IDR_MENU_STATUS                 177
#define IDD_DIALOG_ADD_BLACKLIST        178
#define IDR_CLUSTER_CFG                 179
#define IDD_DIALOG_HISTORY              180
#define IDR_LEFT_CLICK_LOGIN            181
#define IDD_HISTORY_FIND_TOOL_BAR       182
#define IDD_HISTORY_TOOL_BAR            184
#define IDI_BUSY                        185
#define IDI_DIS                         186
#define IDI_LEAVE                       187
#define IDI_NORM                        188
#define IDI_STEALTH                     189
#define IDI_GROUP                       190
#define IDB_ICON_ON                     191
#define IDB_FACE_FRAME                  192
#define IDB_ICON_OFF                    193
#define IDB_ICON_GROUP                  194
#define IDI_OFFLINE                     195
#define IDB_STATUS_BUSY                 196
#define IDB_STATUS_LEAVE                197
#define IDB_STATUS_ONLINE               198
#define IDB_STATUS_HIDE                 199
#define IDB_STATUS_OFFLINE              200
#define IDD_DLG_VIDEO                   201
#define IDD_DLG_NEAR_COMM_CUST          203
#define IDB_PNG_HISTORICAL_DISABLE      204
#define IDB_PNG_HISTORICAL_HOVER        205
#define IDB_PNG_HISTORICAL_NORMAL       206
#define IDB_PNG_HISTORICAL_PRESSED      207
#define IDB_PNG_NEXT_DISABLE            208
#define IDB_PNG_NEXT_HOVER              209
#define IDB_PNG_NEXT_NORMAL             210
#define IDB_PNG_NEXT_PRESSED            211
#define IDB_PNG_LAST_DISABLE            212
#define IDB_PNG_LAST_HOVER              213
#define IDB_PNG_LAST_NORMAL             214
#define IDB_PNG_LAST_PRESSED            215
#define IDB_PNG_PREV_DISABLE            216
#define IDB_PNG_PREV_HOVER              217
#define IDB_PNG_PREV_NORMAL             218
#define IDB_PNG_PREV_PRESSED            219
#define IDB_PNG_FIRST_DISABLE           220
#define IDB_PNG_FIRST_HOVER             221
#define IDB_PNG_FIRST_NORMAL            222
#define IDB_PNG_FIRST_PRESSED           223
#define IDD_DLG_EVALUE                  224
#define IDD_DLG_AUTO_REPLY              225
#define IDD_DLG_MSGMANAGE_FRIEND        226
#define IDB_PNG_SOUND_DISABLE           227
#define IDB_PNG_SOUND_HOVER             228
#define IDB_PNG_SOUND_NORMAL            229
#define IDB_PNG_SOUND_PRESSED           230
#define IDB_PNG_VOICE_DISABLE           231
#define IDB_PNG_VOICE_HOVER             232
#define IDB_PNG_VOICE_NORMAL            233
#define IDB_PNG_VOICE_PRESSED           234
#define IDB_PNG_SOUND_OFF               235
#define IDB_PNG2                        236
#define IDB_PNG_SOUND_ON                236
#define IDB_PNG_VIDEO                   237
#define IDB_PNG_ACCEPT_HOVER            238
#define IDB_PNG_ACCEPT_NORMAL           239
#define IDB_PNG_ACCEPT_PRESSED          240
#define IDB_PNG_REFUSE_HOVER            241
#define IDB_PNG_REFUSED_NORMAL          242
#define IDB_PNG7                        243
#define IDB_PNG_REFUSED_PRESSED         243
#define IDB_PNG_FASTWORD_DISABLE        245
#define IDB_PNG_FASTWORD_HOVER          246
#define IDB_PNG_FASTWORD_NORMAL         247
#define IDB_PNG_FASTWORD_PRESSED        248
#define IDB_PNG_HANGUP_DISABLE          249
#define IDB_PNG_HANGUP_HOVER            250
#define IDB_PNG_HANGUP_NORMAL           251
#define IDB_PNG_HANGUP_PRESSED          252
#define IDD_DLG_HANGUP_NUM_SETTING      253
#define IDB_PNG_SEARCH_DISABLE          254
#define IDB_PNG_SEARCH_HOVER            255
#define IDB_PNG_SEARCH_NORMAL           256
#define IDB_PNG_SEARCH_PRESSED          257
#define IDB_PNG_ADD_GROUP_DISABLE       258
#define IDB_PNG_ADD_GROUP_HOVER         259
#define IDB_PNG_ADD_GROUP_NORMAL        260
#define IDB_PNG_ADD_GROUP_PRESSED       261
#define IDD_DLG_EDIT_NOTICE             262
#define IDD_DLG_MOD_HEAD_ICON           263
#define IDD_DLG_SEL_DEF_HEAD            264
#define IDB_PNG_ROUND_NORMAL            265
#define IDB_PNG_ROUND_SEL               266
#define IDB_PNG_BIG_BROUND_NORMAL       267
#define IDD_DLG_SPECIFY_SEND            268
#define IDB_PNG_FILES_DISABLE           269
#define IDB_PNG_FILES_HOVER             270
#define IDB_PNG_FILES_NORMAL            271
#define IDB_PNG_FILES_PRESSED           272
#define IDD_DLG_SELF_INFO_PREVIEW       273
#define IDD_DIALOG1                     274
#define IDD_DLG_SELF_INFO               274
#define IDB_PNG_GRAYBTN_S_HOVER         275
#define IDB_PNG_GRAYBTN_S_NORMAL        276
#define IDB_PNG_GRAYBTN_S_PRESSED       277
#define IDD_DLG_SELF_INFO_EDIT          278
#define IDD_DLG_FRIEND_INFO             279
#define IDD_DLG_FRINDINFO_ARCH          280
#define IDB_PNG_QUICK_PRESSED           281
#define IDB_PNG_QUICK_NORM              282
#define IDB_PNG_QUICK_HOVER             283
#define IDB_PNG_MSG_NUM_S               284
#define IDD_DIALOG_HINT_CLUSTER_AGREE   285
#define IDB_PNG_STATUS_BUSY_SMALL       286
#define IDB_PNG_STATUS_LEAVE_SMALL      287
#define IDB_PNG_STATUS_HIDE_SMALL       288
#define IDD_DIALOG_PICTURE              289
#define IDD_DIALOG_PICTURE_CLOSE        290
#define IDD_DIALOG_PICTURE_PIC          291
#define IDB_PNG_CLOSE_HOVER             292
#define IDB_PNG_CLOSE_LEAVE             293
#define IDR_ZIPRES1                     294
#define IDB_PNG_MICRO                   295
#define IDB_PNG_VOICE                   296
#define IDB_PNG_GRAYBTN_L_HOVER         297
#define IDB_PNG_GRAYBTN_L_NORMAL        298
#define IDB_PNG_GRAYBTN_L_PRESSED       299
#define IDD_DIALOG_SCREEN_TOOL          300
#define IDD_DIALOG_SCREEN               301
#define IDB_PNG_ARROW_HOVER             302
#define IDB_PNG_ARROW_NORMAL            303
#define IDB_PNG_ARROW_PRESSED           304
#define IDB_PNGDONE_HOVER               305
#define IDB_PNG_DONE_HOVER              305
#define IDB_PNG_DONE_NORMAL             306
#define IDB_PNG_DONE_PRESSED            307
#define IDB_PNG_ELLIPSE_HOVER           308
#define IDB_PNG_ELLIPSE_NORMAL          309
#define IDB_PNG_ELLIPSE_PRESSED         310
#define IDB_PNG_SAVE_HOVER              311
#define IDB_PNG_SAVE_NORMAL             312
#define IDB_PNG_SAVE_PRESSED            313
#define IDB_PNG_RECTANGLE_HOVER         314
#define IDB_PNG_RECTANGLE_NORMAL        315
#define IDB_PNG_RECTANGLE_PRESSED       316
#define IDB_PNG_SENIOR_BTN_HOVER        318
#define IDB_PNG_SENIOR_BTN_NORMAL       319
#define IDB_PNG_SENIOR_BTN_PRESSED      320
#define IDB_PNG_SENIOR_BTN_HOVER_L      321
#define IDB_PNG_SENIOR_BTN_NORMAL_L     322
#define IDB_PNG_SENIOR_BTN_PRESSED_L    323
#define IDB_PNG_SCREEN_CLOSE_HOVER      324
#define IDB_PNG_SCREEN_CLOSE_NORMAL     325
#define IDB_PNG_SCREEN_CLOSE_PRESSED    326
#define IDD_DLG_INTERNAL_FRIENDINFO     327
#define IDB_PNG_SCREEN_FONT_HOVER       328
#define IDB_PNG_SCREEN_FONT_NORMAL      329
#define IDB_PNG_SCREEN_FONT_PRESSED     330
#define IDD_DIALOG_SCREEN_COLOR         331
#define IDB_PNG_SCREEN_SHAPE_SMALL_HOVER 332
#define IDB_PNG_SCREEN_SHAPE_SMALL_NORMAL 333
#define IDB_PNG_SCREEN_SHAPE_SMALL_PRESSED 334
#define IDB_PNG_SCREEN_SHAPE_NORMAL_HOVER 335
#define IDB_PNG_SCREEN_SHAPE_NORMAL_NORMAL 336
#define IDB_PNG_SCREEN_SHAPE_NORMAL_PRESSED 337
#define IDB_PNG_SCREEN_SHAPE_BIG_HOVER  338
#define IDB_PNG_SCREEN_SHAPE_BIG_NORMAL 339
#define IDB_PNG_SCREEN_SHAPE_BIG_PRESSED 340
#define IDB_PNG_SCREEN_UNDO_HOVER       341
#define IDB_PNG_SCREEN_UNDO_NORMAL      342
#define IDB_PNG_SCREEN_UNDO_PRESSED     343
#define IDD_DLG_SEL_CUSTOM_HEAD         344
#define IDB_PNG_BACKEND_HOVER           345
#define IDB_PNG_BACKEND_NORMAL          346
#define IDB_PNG_BACKEND_PRESSED         347
#define IDB_PNG_CUSTSER_HOVER           348
#define IDB_PNG_CUSTSER_NORMAL          349
#define IDB_PNG_CUSTSER_PRESSED         350
#define IDB_PNG_P2P_CHAT_NORMAL         353
#define IDB_PNG_P2P_CHAT_PRESSED        354
#define IDB_PNG_P2P_CHAT_HOVER          355
#define IDB_PNG_P2P_VIDEO_HOVER         356
#define IDB_PNG_P2P_VIDEO_NORMAL        357
#define IDB_PNG_P2P_VIDEO_PRESSED       358
#define IDB_PNG_SENDFILE_HOVER          359
#define IDB_PNG_SENDFILE_NORMAL         360
#define IDB_PNG_SENDFILE_PRESSED        361
#define IDR_MINI139_SRC                 500
#define IDB_OLEIMAGE                    501
#define IDR_OLEIMAGE                    502
#define IDC_EDIT_LENGTH                 1000
#define IDC_EDIT_SMS                    1001
#define IDC_EDIT_INTERVAL               1002
#define IDC_BUTTON_BEGIN                1003
#define IDC_BUTTON_END                  1004
#define IDC_BUTTON_CONFIG               1005
#define IDC_EDIT_CONFIG                 1006
#define IDD_DIALOG_TEST                 1007
#define IDC_BTN_TEST                    1008
#define IDC_STATIC_TOTAL_TIME           1009
#define IDC_BTN_MERCHANT_ENTRANCE       1009
#define IDC_STATIC_TOTAL_CNT            1010
#define IDC_STATIC_TOTAL_LEN            1011
#define IDC_EDIT_EMAIL                  1012
#define IDC_FOLDER                      1013
#define IDC_STATIC_TITLE                1014
#define IDC_EDIT1                       1015
#define IDC_EDIT_TITLE                  1016
#define IDC_EDIT_KEYWORD                1017
#define IDC_SPLITTER1                   1018
#define IDC_EDIT_SIGN                   1019
#define IDC_EDIT_MARK                   1020
#define IDC_OK                          1021
#define IDC_EDIT_PASS                   1022
#define IDC_ADD_AGAIN                   1023
#define IDC_BTN_SEARCH                  1024
#define IDC_EDIT_DESCRIPTION            1025
#define IDC_STATIC_FRAME                1026
#define IDC_BTN_PROFILE                 1027
#define IDC_CHECK_PSWD                  1028
#define IDC_BTN_PREV                    1029
#define IDC_EDIT_TEL                    1030
#define IDC_BTN_CLUSTERMEMBER           1031
#define IDC_BTN_ADD                     1032
#define IDC_BTN_NEXT_PAGE               1033
#define IDC_EDIT_ADDRESS                1034
#define IDC_BTN_SECURITY                1035
#define IDC_BTN_LAST_PAGE               1036
#define IDC_BTN_CLUSTERINFO             1037
#define IDC_EDIT_SELFINFO               1038
#define IDC_STATIC_LINE                 1039
#define IDC_IMAGEPREVIEW                1040
#define IDC_COMBO_SEX                   1041
#define IDC_STATIC_TIP                  1042
#define IDC_STATIC_SEX                  1043
#define IDC_STATIC_TIP3                 1043
#define IDC_BUTTON_SELFACE              1044
#define IDC_STATIC_TIP2                 1045
#define IDC_COMBO_COUNTY                1046
#define IDC_EXPLORER1                   1047
#define IDC_FILESIZE                    1048
#define IDC_STATIC_USERINFO             1049
#define IDC_EDIT_INTRO                  1050
#define IDC_STATIC_STATE                1050
#define IDC_STATIC_STATUS_GROUP         1050
#define IDC_EDIT_BULITIN                1051
#define ID_BUTTON_REGISTER              1052
#define IDC_BTN_BLOG                    1053
#define IDC_COMBO_TYPE                  1054
#define IDC_BUTTON_ALL                  1055
#define ID_BUTTON_FORGET_PWD            1056
#define IDC_CHECK_HIDE                  1057
#define IDC_BUTTON_CLEAR                1058
#define IDC_BTN_DELMEMBER               1059
#define IDC_BUTTON_CANCEL               1060
#define IDC_BUTTON_I                    1061
#define IDC_BUTTON_MODIFY_ADDR          1062
#define IDC_BUTTON_SEARCH               1063
#define IDC_BUTTON_SENDMSG              1064
#define IDC_BTN_RIGHT                   1065
#define IDC_BTN_NEAR_COMM_CUST          1066
#define IDC_BTN_FIRST_PAGE              1067
#define IDC_CHECK_LOGIN                 1068
#define IDC_LIST_CLUSTER                1069
#define IDC_BUTTON_B                    1070
#define IDC_BUTTON_SHOPINFO             1071
#define IDC_COMBO_NO                    1072
#define IDC_BTN_DELMANAGE               1073
#define IDC_COMBO_USERNAME              1074
#define ID_BUTTON_LOGIN                 1075
#define IDC_BTN_ADDFRIEND               1076
#define ID_BUTTON_CANCEL                1077
#define IDC_BTN_SETMANAGE               1078
#define IDC_CHECK_FRIEND                1079
#define IDC_EDIT_CREATOR                1080
#define IDC_COMBO_STATUS                1081
#define IDC_EDIT_NAME                   1082
#define IDC_SETMEMBERS                  1083
#define IDC_EDIT_CNAME                  1084
#define IDC_PROGRESS1                   1085
#define IDC_STATIC_INFO2                1086
#define IDC_STATIC1                     1087
#define IDC_STATIC2                     1088
#define IDC_STATIC_SPEED                1089
#define IDC_STATIC3                     1090
#define IDC_STATIC4                     1091
#define IDC_STATIC_TEXTBOX              1092
#define IDC_EDIT_SHORTCUT               1093
#define IDC_BUTTON_OK                   1094
#define IDC_STATIC_PIC                  1095
#define IDC_LIST_EMOTION                1096
#define IDC_BUTTON_ADD                  1097
#define IDC_BUTTON_DEL                  1098
#define IDC_BUTTON_MODIFY               1100
#define IDC_BUTTON_CLOSE                1101
#define IDC_CHECK1                      1102
#define IDC_CHECK_AUTOSTART             1103
#define IDC_CHECK_RECIVE                1106
#define IDC_TIME_BGN                    1107
#define IDC_DATETIMEPICKER_BIRTHDAY     1108
#define IDC_TIME_END                    1109
#define IDC_DATETIMEPICKER_BIRTH        1110
#define IDC_CHECK_STATUS                1111
#define IDC_DATE_BGN                    1112
#define IDC_DATE_END                    1113
#define IDC_BTN_DEL                     1114
#define IDC_NEXT                        1115
#define IDC_BTN_DEL2                    1115
#define IDC_COMBO_PROVINCE              1116
#define IDC_BTN_REFRESH                 1117
#define IDC_COMBO_CITY                  1118
#define IDC_CLOSE                       1120
#define IDC_EDIT_USERNAME               1121
#define IDC_BTN_FIND                    1122
#define IDC_EDIT_NICKNAME               1123
#define IDC_COMBO_CAREER                1124
#define IDC_BTN_FIND2                   1124
#define IDC_BTN_RET                     1124
#define IDC_PREVIEWNAME                 1125
#define IDC_BTN_SUBMIT                  1126
#define IDC_BTN_CLUSTERPIC_VIEW         1128
#define IDC_BUTTON_HOME                 1129
#define IDC_BTN_TEMP_VIEW               1129
#define IDC_BTN_FRIENDPIC_VIEW          1130
#define IDC_BTN_BIGHEAD                 1131
#define IDC_BTN_ACCEPT_VIEW             1132
#define IDC_BUTTON_SMS                  1133
#define IDC_BTN_ADMIN_SETTING           1134
#define IDC_BTN_SET_ADMIN               1135
#define IDC_BTN_COMMON                  1136
#define IDC_BTN_DIR                     1137
#define IDC_BTN_CFG                     1138
#define IDC_BTN_MICRO                   1139
#define IDC_BTN_ALL                     1140
#define IDC_BTN_SAVE                    1141
#define IDC_BTN_SAVE2                   1142
#define IDC_COMBO_DAY                   1143
#define IDC_BUTTON_CFG                  1144
#define IDC_BUTTON_PREV                 1145
#define IDC_BUTTON_LOCALFILE            1146
#define IDC_BUTTON_BIGHEAD              1147
#define IDC_BTN_CLUSTER_ALUBM           1148
#define IDC_BUTTON_RIGHT                1149
#define IDC_BTN_WRITEARTICLE            1150
#define IDC_BUTTON5                     1151
#define IDC_BTN_DONE                    1151
#define IDC_BTN_MODIFY_INFO             1152
#define IDC_BTN_CLEAR                   1153
#define IDC_BTN_SYS_MSG                 1154
#define IDC_BTN_CANCLE                  1155
#define IDC_EXPLORER_BLOG               1157
#define IDC_BUTTON_NEXT                 1158
#define IDC_BUTTON_WEBURL               1159
#define IDC_BTN_CLUSTER_HOME            1160
#define IDC_BUTTON_WEBPIC               1161
#define IDC_BUTTON_BACKUP               1162
#define IDC_BUTTON_WRITE                1163
#define IDC_BUTTON_RIGHT3               1164
#define IDC_BTN_UPPICTURE               1165
#define IDC_BUTTON6                     1166
#define IDC_BTN_CANCEL_ADMIN            1167
#define IDC_BTN_VOICE                   1168
#define IDC_BTN_FILEFOLDER              1169
#define IDC_BUTTON_LAST                 1171
#define IDC_BUTTON_139PIC               1172
#define IDC_BUTTON_SETTING              1173
#define IDC_BUTTON_MAILINVITE           1174
#define IDC_BTN_WRITEARTICLE2           1175
#define IDC_BTN_MYARTICLE               1176
#define IDC_BUTTON7                     1177
#define IDC_BTN_LOGIN                   1178
#define IDC_BTN_MYPICTURE               1179
#define IDC_BUTTON8                     1180
#define IDC_BTN_ADD_MEMBER              1181
#define IDC_BTN_FILE                    1182
#define IDC_BUTTON_139NOTE              1183
#define IDC_BTN_MYARTICLE2              1184
#define IDC_BTN_MEDIA                   1185
#define IDC_BTN_FAST_WORD               1186
#define IDC_STATIC_LOGINERROR           1187
#define IDC_BTN_AUTO_REPLY              1188
#define IDC_STATIC_139                  1189
#define IDC_BTN_SOFTWARE_UPDATE         1190
#define IDC_BTN_SYS_ADD                 1191
#define IDC_STATIC_LOGINGIF             1192
#define IDC_BTN_BLOGSEARCH              1193
#define IDC_DHTMLEDIT1                  1194
#define IDC_DHTMLEDIT_BLOG              1195
#define IDC_BUTTON_C                    1196
#define IDC_BUTTON_U                    1197
#define IDC_COMBO1                      1198
#define IDC_COMBO2                      1199
#define IDC_COMBO_VOICE_OUTPUT          1199
#define IDC_GROUP                       1200
#define IDC_COMBO_DIR                   1201
#define IDC_COMBO4                      1202
#define IDC_COMBO_CAMERA_SEL            1202
#define IDC_EDIT2                       1203
#define IDC_EDIT_BIRTHDAY               1204
#define IDC_COMBO_VIEW                  1205
#define IDC_EDIT_BODY                   1206
#define IDC_COMBO5                      1207
#define IDC_COMBO_CATALOG               1209
#define IDC_BUTTON_POST                 1210
#define IDC_TREE_CHILD_NODE             1211
#define IDC_COMBO_IMSERVER              1212
#define IDC_LIST1                       1213
#define IDC_BUTTON_RESET                1214
#define IDC_LIST_LOG                    1215
#define IDC_CHECK_PASS                  1216
#define IDC_BUTTON_SAVE                 1217
#define IDC_CHECK_FRIEND_ONLINE_VOICE   1217
#define IDC_STATIC_NICKNAME             1218
#define IDC_CHECK_SYS_MSG_VOICE         1218
#define IDC_CHECK_SHOCK_SCREEN_VOICE    1219
#define IDC_RE_SEND                     1220
#define IDC_BUTTON_BLOG                 1221
#define IDC_BUTTON_PIC                  1222
#define IDC_BUTTON_STATUS               1223
#define IDC_BUTTON_PIC2                 1224
#define IDC_BUTTON_STATUS3              1224
#define IDC_BUTTON_STATUS2              1225
#define IDC_BUTTON_REFRESH              1226
#define IDC_BUTTON_SCRN                 1227
#define IDC_STATIC_STATUS               1228
#define IDC_BUTTON_SCRN2                1228
#define IDC_BUTTON_SCRN_HOTKEY          1228
#define IDC_BUTTON_ACTION               1229
#define IDC_IMAGE_TITLE                 1230
#define IDC_BUTTON_LINK                 1231
#define IDC_IMAGE_TOOLBTN               1232
#define IDC_RE_HISTORY                  1233
#define IDC_STATIC_HIDE                 1234
#define IDC_BTN_HISTORY                 1235
#define IDC_BTN_HOME                    1236
#define IDC_STATIC_HIDE2                1237
#define IDC_COMBO_FONTNAME              1238
#define IDC_STATIC_CUR                  1239
#define IDC_BTN_GOLD                    1240
#define IDC_STATIC_EXPLAIN              1241
#define IDC_COMBO_FONTSIZE              1242
#define IDC_RADIO_Very_satisfied        1243
#define IDC_BTN_MSG                     1244
#define IDC_RADIO_Satisfied             1245
#define IDC_BTN_SEND                    1246
#define IDC_RADIO_General               1247
#define IDC_STATIC_BLOG                 1248
#define IDC_RADIO_Unsatisfy             1249
#define IDC_STATIC_TAG                  1250
#define IDC_RADIO_Extremely_dissatisfied 1251
#define IDC_BTN_BOLD                    1252
#define IDC_EDIT_SUGGEST                1253
#define IDC_STATIC_ALBUM                1254
#define IDC_STATIC_FONT                 1255
#define IDC_STATIC_ZONE                 1256
#define IDC_RICHEDIT21                  1257
#define IDC_RICHEDIT_TEXT               1258
#define IDC_STATIC_SHOP                 1259
#define IDC_HOTKEY3                     1260
#define IDC_HOTKEY_SNAPSHOT             1261
#define IDC_STATIC_BTN_AREA             1262
#define IDC_STATIC_LOGINPAUSE           1263
#define IDC_CHECK_SHAKE                 1264
#define IDC_STATIC_FONT_ONLINE          1265
#define IDC_EDIT_SEX                    1266
#define IDC_RICHEDIT_TEXT_ONLINE        1267
#define IDC_STATIC_TEMP_COUNT           1268
#define IDC_EDIT_TIME                   1269
#define IDC_BTN_INVITE                  1270
#define IDC_STATIC_FONT_OFFLINE         1271
#define IDC_STATIC_TEMP_SIZE            1272
#define IDC_CANCEL                      1273
#define IDC_RICHEDIT_TEXT_OFFINE        1274
#define IDC_RICHEDIT_TEXT_OFFLINE       1275
#define IDC_BTN_VISIT                   1276
#define IDC_STATIC_CLUSTERPIC_COUNT     1277
#define IDC_PREV                        1278
#define IDC_STATIC_FRIENDPIC_COUNT      1279
#define IDC_BTN_CARD                    1280
#define IDC_CHECK_WARN                  1283
#define IDC_STATIC_ACCEPT_COUNT         1284
#define IDC_STATIC_HIDE1                1285
#define IDC_BTN_ADMIN                   1286
#define IDC_STATIC_CLUSTERPIC_SIZE      1287
#define IDC_HISTORY                     1288
#define IDC_STATIC_FRIENDPIC_SIZE       1289
#define IDC_STATIC_MAIN_TAB             1290
#define IDC_STATIC_PAGE                 1291
#define IDC_STATIC_ACCEPT_SIZE          1292
#define IDC_STATIC_AREA                 1293
#define IDC_BTN_WEBSMS                  1294
#define IDC_STATIC_BASIC_SETTING        1295
#define IDC_BTN_SENDFILE                1296
#define IDC_STATIC_SECURITY_SETTING     1297
#define IDC_BUTTON_FONT                 1298
#define IDC_STATIC_COL                  1299
#define IDC_BUTTON_FACE                 1300
#define IDC_COMBO_AGE                   1301
#define IDC_BUTTON_MAGIC                1302
#define IDC_LIST_RECENT                 1303
#define IDC_BTN_FACESEL                 1304
#define IDC_SPIN1                       1305
#define IDC_SPIN_TIME                   1306
#define IDC_RADIO1                      1307
#define IDC_RADIO2                      1308
#define IDC_BUTTON_FIRST                1309
#define IDC_RADIO3                      1310
#define IDC_BUTTON_FIRST2               1311
#define IDC_STATIC_FACE                 1312
#define IDC_STATIC_DOMAIN               1313
#define IDC_RADIO4                      1314
#define IDC_EDIT_CAREER                 1315
#define IDC_STATIC_FLAG                 1316
#define IDC_RADIO5                      1317
#define IDC_RADIO_LOW                   1317
#define IDC_EDIT_PASS1                  1318
#define IDC_STATIC_INTRO                1319
#define IDC_EDIT_PASS2                  1320
#define IDC_STATIC_SETTING              1321
#define IDC_STATIC_1                    1322
#define IDC_STATIC_2                    1323
#define IDC_STATIC_REFRESH              1324
#define IDC_STATIC_3                    1324
#define IDC_LIST_FRIEND                 1325
#define IDC_STATIC_4                    1325
#define IDC_LIST_CONTACTS               1326
#define IDC_STATIC_5                    1326
#define IDC_CHECK_MAGIC                 1327
#define IDC_STATIC_6                    1327
#define IDC_STATIC_NOTICE               1328
#define IDC_STATIC_7                    1328
#define IDC_EDIT_ID                     1329
#define IDC_STATIC_NOTICE_TEXT          1329
#define IDC_STATIC_8                    1329
#define IDC_CHECK_MAGIC2                1330
#define IDC_STATIC_9                    1330
#define IDC_CHECK_MINI_PICBROADCAST     1331
#define IDC_STATIC_10                   1331
#define IDC_LIST_ADD                    1332
#define IDC_STATIC_11                   1332
#define IDC_UPDATE                      1333
#define IDC_STATIC_12                   1333
#define IDC_LIST_FRIEND2                1334
#define IDC_STATIC_13                   1334
#define IDC_STATIC_14                   1335
#define IDC_STATIC_RIGHT                1336
#define IDC_STATIC_15                   1336
#define IDC_CHECK_REFUSE                1337
#define IDC_STATIC_16                   1337
#define IDC_BUTTON_ADD_ADDR             1338
#define IDC_EDIT_MAINPAGE               1339
#define IDC_STATIC_LEFT                 1340
#define IDC_RE_MSG                      1341
#define IDC_COMBO_WEATHER               1342
#define IDC_COMBO_EMOTION               1343
#define IDC_EDIT_QQNUM                  1344
#define IDC_STATIC_DATE                 1345
#define IDC_COMBO_COMMENT               1346
#define IDC_EDIT_MSN_NUM                1347
#define IDC_STATIC_FROM                 1348
#define IDC_COMBO_AUTH                  1349
#define IDC_EDIT_PHOTO                  1350
#define IDC_STATIC_TO                   1351
#define IDC_DIALOG_CLUSETR_AUTH         1352
#define IDC_BUTTON_MYDISK               1353
#define IDC_EDIT_COMPANY                1354
#define IDC_STATIC_TOPLINE              1355
#define IDC_DIALOG_CLUSETR_CHECK        1356
#define IDC_COMBO_GAME                  1357
#define IDC_EDIT_SCHOOL                 1358
#define IDC_LIST_MSG                    1359
#define IDD_DIALOG_FACE                 1360
#define IDC_COMBO_TOP                   1361
#define IDC_STATIC_TIME                 1362
#define IDC_BTN_EXPORT                  1363
#define IDC_EDIT_BLOG                   1364
#define IDD_DIALOG_CUSTOMFACE_PREVIEW   1365
#define IDC_STATIC_INFO                 1366
#define IDC_STATIC_ID                   1367
#define IDC_STATIC_EMOTION              1368
#define IDC_EDIT_NOTE                   1369
#define IDC_STATIC_FIRST                1370
#define IDC_STATIC_MORE                 1371
#define IDD_DIALOG_CUSTOMEMOTION_INFO   1372
#define IDC_STATIC_TIP1                 1373
#define IDC_EDIT1_CAREER                1374
#define IDC_STATIC_PREV                 1376
#define IDC_SEND                        1377
#define IDC_EDIT_TAG                    1378
#define IDC_BUTTON_APPLY                1379
#define IDC_STATIC_ID2                  1380
#define IDC_STATIC_NEXT                 1381
#define IDC_REFRESH                     1382
#define IDC_COMBO_MYTAG                 1383
#define IDC_BUTTON_DEL_ADDR             1384
#define IDC_STATIC_LAST                 1386
#define IDD_P2PTALK_TOOLBAR             1387
#define IDC_BUTTON_MYADDRESS            1388
#define IDC_STATIC_ALL                  1389
#define IDD_P2P_TOOLBAR                 1390
#define IDC_STATIC_TYPE_TIP             1391
#define IDC_UPLOADPICACTIVEXCTRL1       1392
#define IDC_BUTTON_DEL_ADDR2            1393
#define IDC_BUTTON_MINILINK             1394
#define IDC_EDIT_AUTH                   1395
#define IDD_TAB_PAGE1                   1396
#define IDC_STATIC_TYPE                 1397
#define IDC_STATIC_PROGRESS             1398
#define IDC_CHECK_ADD                   1399
#define IDC_STATIC_SHOW                 1400
#define IDD_DIALOG_SELFFACE             1401
#define IDC_STATIC_HINT                 1402
#define IDD_DIALOG_MFACE                1403
#define IDC_EDIT_MSG                    1404
#define IDC_EDIT_INFO                   1405
#define IDD_SA_PAGE6                    1406
#define IDC_STATIC_LINK                 1407
#define IDC_SCROLLBAR1                  1408
#define IDC_STATIC_LINK2                1409
#define IDD_PREVIEW_DIALOG              1410
#define IDC_STATIC_LINE1                1411
#define IDC_STATIC_LINE2                1412
#define IDD_DIALOG_PROGRESS1            1413
#define IDD_DIALOG_PROGRESS2            1414
#define IDD_DIALOG_PROGRESS3            1415
#define IDC_BUTTON_HELPER               1416
#define IDD_SA_PAGE7                    1417
#define IDC_CTRLENTER                   1418
#define IDC_ENTER                       1419
#define IDD_DIALOG_MYPICTURE            1420
#define IDC_STATIC_RANGE                1421
#define IDC_CTRLENTER2                  1422
#define IDC_HOTKEY_CUSTOM               1423
#define IDC_STATIC_KEYWORD              1424
#define IDC_STATIC_MSG                  1425
#define IDC_MSG                         1426
#define IDC_BTN_DETAIL                  1427
#define IDC_STATIC_TOTAL                1428
#define IDC_BTN_DETAIL2                 1429
#define IDD_DIALOG_FRIENDLOG_ENTRY1     1430
#define IDD_DIALOG_FRIENDLOG_VIEW       1431
#define IDC_BTN_ALBUM                   1432
#define IDC_STATIC_WINDOW               1433
#define IDD_DIALOG_INVITE_CONTACT       1434
#define IDC_STATIC_LEVEL                1435
#define IDD_DIALOG_USERGUIDE            1436
#define IDC_STATIC_LEVEL2               1436
#define IDC_BTN_DISCUSS                 1437
#define IDD_DIALOG_139MSG               1438
#define IDD_DIALOG_139NOTE              1439
#define IDC_STATIC_CLUSTERINFO          1440
#define IDC_CLUSTERHEAD                 1441
#define IDD_DIALOG_139NOTE1             1442
#define IDC_EDIT_CLUSTERNAME            1443
#define IDD_DIALOG_SELFFACE1            1444
#define IDD_DIALOG_FAMILYFACE           1445
#define IDC_EDIT_CLUSTERNO              1446
#define IDD_TAB_PAGE3                   1447
#define IDC_EDIT_CLUSTERCREATOR         1448
#define IDC_CMB_OBJECT                  1449
#define IDC_EDIT_CLUSTER_SITE           1450
#define IDD_P2PAUDIO_PANEL              1451
#define IDC_STATIC_LOGO2                1452
#define IDC_CMB_ACTIONS                 1453
#define IDD_FLOOR_WOKU                  1454
#define IDC_STATIC_LBL                  1455
#define IDD_FLOOR_WEBPAGE               1456
#define IDC_BTN_EDITACTION              1457
#define IDD_FLOOR_RECENT                1458
#define IDC_BTN_EDITACTION2             1459
#define IDC_BTN_LOADACTION              1460
#define IDC_LIST                        1461
#define IDD_MAIN_TOOL                   1462
#define IDD_P2PVEDIO_PANEL              1463
#define IDC_BTN_SITE                    1464
#define IDC_BTN_CANCEL                  1465
#define IDC_BTN_FOLD                    1466
#define IDD_MAIN_AD                     1467
#define IDC_EDT_LINKURL                 1468
#define IDD_SA_PAGE8                    1469
#define IDD_SA_PAGE_VIDEO               1470
#define IDC_BMP_LINKRES                 1471
#define IDD_DIALOG_USERCARD             1472
#define IDC_BUTTON_LEFT                 1473
#define IDD_DIALOG_SELFINFO             1474
#define IDC_BUTTON_LEFT2                1475
#define IDC_TAB1                        1476
#define IDD_DIALOG_CLUSTER_SETTING      1477
#define IDC_TAB_SYS_SETTING             1478
#define IDC_TAB_GROUP                   1479
#define IDC_SLIDER1                     1480
#define IDD_CLUSTER_INFO                1481
#define IDC_SPLITTER                    1482
#define IDC_BUTTON_RIGHT2               1483
#define IDC_CHECK_NEED_RUN              1484
#define IDC_SLIDER2                     1485
#define IDC_COMBO_TAG                   1486
#define IDC_CHECK_TOP                   1487
#define IDC_STATIC_ETCHED2              1488
#define IDC_EXPLORER3                   1489
#define IDC_EXPLORER_HELP               1490
#define IDD_CLUSTER_PROFILE             1491
#define IDC_STATIC_ETCHED1              1492
#define IDC_CHECK2                      1493
#define IDC_CHECK_FRD_ART               1494
#define IDD_CLUSTER_SECURITY            1495
#define IDD_CLUSTER_MEMBER              1496
#define IDC_BUTTON_ARTICLE              1497
#define IDC_CHECK_FRD_PIC               1498
#define IDC_DIALOG_CLUSETR_MANAGE       1499
#define IDC_RADIO_PUBLIC                1500
#define IDC_BUTTON_ARTICLE2             1501
#define IDC_RADIO_FRIEND                1502
#define IDD_WIZARD_CLUSTER_SYS_SETTING  1503
#define IDC_RADIO_PRIVATE               1504
#define IDD_WIZARD_CLUSTER_SYS_COMMON   1505
#define IDC_LIST_LOCAL                  1506
#define IDC_CLUSTER_OPR                 1507
#define IDD_WIZARD_CLUSTER_SYS_SECURITY 1508
#define IDC_EDIT_FWTK                   1509
#define IDC_ADVANCED_SETTING            1510
#define IDD_WIZARD_SYS_SECURITY_PWD     1511
#define IDC_BUTTON_NEW                  1512
#define IDC_PROMPT_USERNAME             1513
#define IDD_WIZARD_SYS_SECURITY_VERIFY  1514
#define IDC_COMBO_SEARCH                1515
#define IDC_PROMPT_NICKNAME2            1516
#define IDD_WIZARD_SYS_SECURITY_MSGLOG  1517
#define IDC_BUTTON_EDIT                 1518
#define IDC_PROMPT_PASSWORD             1519
#define IDC_PROMPT_PASSWORD1            1520
#define IDD_WIZARD_SYS_SECURITY_FILE_TRANS 1521
#define IDC_BUTTON_DELETE               1522
#define IDC_PROMPT_PASSWORD2            1523
#define IDD_WIZARD_SYS_COMMON_BASIC     1524
#define IDC_LIST_WEB                    1525
#define IDC_RADIO_MALE                  1526
#define IDD_WIZARD_SYS_COMMON_VOICE_LOG 1527
#define IDC_EXPLORER_WEB                1528
#define IDC_RADIO_FEMALE                1529
#define IDD_WIZARD_SYS_COMMON_MSG_LOG   1530
#define IDC_EXPLORER_LOCAL              1531
#define IDC_EDIT_PATH                   1532
#define IDC_PROMPT_PASSWORD3            1533
#define IDC_PROMPT_EAMIL                1534
#define IDC_LBL_MSG                     1535
#define IDD_WIZARD_SYS_COMMON_AUDIO     1536
#define IDC_BUTTON_PATH                 1537
#define IDC_XPICTURE1                   1538
#define IDD_WIZARD_SYS_COMMON_FILE      1539
#define IDC_BUTTON_EXPORT               1540
#define IDC_LBL_SEX                     1541
#define IDD_WIZARD_SYS_COMMON_SOFT_UPDATE 1542
#define IDC_LBL_USERNAME                1543
#define IDD_DIALOG_TAB_SEARCH           1544
#define IDC_BUTTON_BIGPHOTO             1545
#define IDC_LBL_NICKNAME                1546
#define IDC_EDIT_LABEL                  1547
#define IDC_LBL_PSW1                    1548
#define IDC_BUTTON_MENU                 1549
#define IDC_LBL_PSW2                    1550
#define IDD_WIZARD_SYS_COMMON_AUTO_REPLY 1551
#define IDC_BUTTON_PICTURE_ENTRY        1552
#define IDC_LBL_EMAIL                   1553
#define IDC_BUTTON_ARTICLE_ENTRY        1555
#define IDC_PROMPT_PSW2                 1556
#define IDC_BUTTON_MYPICTURE            1558
#define IDC_LBL_MORE                    1559
#define IDD_WIZARD_AUTO_ACCEPT          1560
#define IDC_BUTTON_MYARTICLE            1561
#define IDD_DLG_AUTO_REPLY1             1562
#define IDD_DLG_FAST_WORD               1563
#define IDC_LBL_NAME                    1564
#define IDC_DIALOG_EXIT_WARNING         1565
#define IDC_BUTTON_UPPIC                1566
#define IDD_DLG_MSGMANAGE               1566
#define IDC_LBL_IP                      1567
#define IDC_EDIT_TO                     1568
#define IDTEST                          1569
#define IDC_INVITE                      1570
#define IDC_EDIT_URL                    1571
#define IDC_CHECK_FAMILY_FLAG           1572
#define IDC_EDIT_TO2                    1573
#define IDC_HOTKEY_MSG                  1574
#define IDC_HOTKEY_DEFAULT              1575
#define IDC_STATIC_DOWNLOAD             1576
#define IDC_FILETRANS_PROGRESS          1577
#define IDC_STATIC_ICON                 1578
#define IDC_LINK_FAMILYHOME             1579
#define IDC_STATIC_HOME                 1580
#define IDC_BUTTON_                     1581
#define IDC_BTN_HEAD_MODIFY             1582
#define IDC_EDIT3                       1583
#define IDC_EDIT4                       1584
#define IDC_EDIT5                       1585
#define IDC_BUTTON3                     1586
#define IDC_BTN_ARROW                   1586
#define IDC_BUTTON_ENTERSHOP            1587
#define IDC_BTN_SYS_MENU                1588
#define IDC_BTN_START_COMM              1589
#define IDC_LBL_MSG1                    1590
#define IDC_BTN_SNATCH                  1591
#define IDC_BUTTON4                     1592
#define IDC_BUTTON_PERSONINFO           1593
#define IDC_BTN_SYS_SET                 1594
#define IDC_BTN_VIEW_CHAT_LOG           1595
#define IDC_EDIT6                       1596
#define IDC_EDT_MAXSPEED                1597
#define IDC_RE_MESSAGE                  1598
#define IDC_CHECK_ALLOW                 1599
#define IDC_STATIC_CREATE               1600
#define IDC_EDIT_DIR                    1601
#define IDC_LIST_DIR                    1602
#define IDC_RADIO_RECVNOSHOW            1603
#define IDC_RADIO_RECVANDSHOW           1604
#define IDC_BUTTON_CREATE               1605
#define IDC_RADIO_RECVNOSHOW2           1606
#define IDC_BTN_STOP                    1607
#define IDC_EDIT_CONTENT                1608
#define IDC_BTN_ANSWER                  1608
#define IDC_BTN_VEDIO                   1609
#define IDC_BTN_LEVEL                   1610
#define IDC_BTN_AUDIO                   1611
#define IDC_AVATAR                      1612
#define IDC_SLIDER_HORN                 1613
#define IDC_EXPLORER_SERVICES           1614
#define IDC_SLIDER_SPEAKER              1615
#define IDC_ICON_HORN                   1616
#define IDC_STATIC_SERVICES             1617
#define IDC_ICON_SPEAKER                1618
#define IDC_COMBO_VEDIO                 1619
#define IDC_STATIC_ART                  1620
#define IDC_VEDIO_SELF                  1621
#define IDC_STATIC_NICK                 1622
#define IDC_VEDIO_FRIEND                1623
#define IDC_STATIC_VEDIO                1624
#define IDC_STATIC_SIGN                 1625
#define IDC_STATIC_B1                   1626
#define IDC_STATIC_BIND                 1627
#define IDC_STATIC_B2                   1628
#define IDC_STATIC_B3                   1629
#define IDC_STATIC_HEAD                 1630
#define IDC_LIST2                       1631
#define IDC_LIST_SMS                    1632
#define IDC_STATIC_NUM                  1633
#define IDC_STATIC_MOBILE               1634
#define IDC_EDIT_SHOWSMS                1635
#define IDC_STATIC_JOB                  1635
#define IDC_STATIC_VER                  1636
#define IDC_STATIC_DEPART               1636
#define IDC_EXPLORER_AVATAR             1637
#define IDC_STATIC_AVATAR               1638
#define IDC_SHOCKWAVEFLASH1             1639
#define IDC_STATIC_PSW                  1640
#define IDC_STATIC_USERNAME             1641
#define IDC_STATIC_PSW2                 1642
#define IDC_CHECK_AUTO_LOGIN            1643
#define IDC_LIST4                       1644
#define IDC_STATIC_LIMIT                1645
#define IDC_WEB_AD                      1646
#define IDC_BUTTON_HISTORY              1647
#define IDC_STATIC_MEMBER               1648
#define IDC_STATIC_CLUSTER              1649
#define IDC_TAB_INFO                    1650
#define IDC_STATIC_CLUSTER2             1651
#define IDC_STATIC_EXIT                 1652
#define IDC_TAB_HISTORY                 1653
#define IDC_EDIT_HISTORY_ALL            1654
#define IDC_STATIC_GROUP                1655
#define IDC_COMBO_GROUP                 1656
#define IDC_BUTTON_HISTORY_FIND         1657
#define IDC_EDIT_SEARCH                 1658
#define IDC_STATIC_FRAME_VIEW           1659
#define IDC_STATIC_HISTORY_PAGE_INFO    1660
#define IDC_BUTTON_CHANGE_ICON          1661
#define IDC_EDIT_PHONE                  1662
#define IDC_STATIC_CLUSTERID            1663
#define IDC_EDIT_CLUSTERINFO            1664
#define IDC_COMBO_KINDS                 1665
#define IDC_EDIT_LISTCTL                1666
#define IDC_STATIC_CREATOR              1667
#define IDC_EDIT_CLUSTERSIGN            1668
#define IDC_RADIO_ALL                   1669
#define IDC_EDIT_CLUSTERSIGN2           1669
#define IDC_RADIO_VERIFY                1670
#define IDC_RADIO_NONE                  1671
#define IDC_BTN_DEL_MEMBER              1672
#define IDC_STATIC_FRAME_COMMON         1673
#define IDC_BUTTON_SOUND                1674
#define IDC_STATIC_FRAME_SECURITY       1675
#define IDC_BUTTON_SHAKE                1676
#define IDC_BTN_PWD                     1677
#define IDC_BUTTON_SCORE                1678
#define IDC_BTN_VERIFY                  1679
#define IDC_STATIC_BOTTOM               1680
#define IDC_STATIC_UNDER                1681
#define IDC_BTN_MSG_LOG                 1682
#define IDC_EDIT_CLUSER_NICKNAME        1683
#define IDC_BTN_FILE_TRANSFER           1684
#define IDC_RADIO_REC_POP               1685
#define IDC_BTN_MSGLOG                  1686
#define IDC_RADIO_MID                   1687
#define IDC_STATIC_TEXT                 1688
#define IDC_LIST_SEND_COUNT             1691
#define IDC_LIST_OUTPUT                 1692
#define IDC_BTN_PREV_PAGE               1693
#define IDC_STATIC_NAME                 1694
#define IDC_STATIC_NAME2                1695
#define IDC_STATIC_EXT                  1695
#define IDC_EDIT_PAGE_NO                1696
#define IDC_DIR_TREE                    1697
#define IDC_STATIC_PAGE_COUNT           1699
#define IDC_STATIC_PASS2                1700
#define IDC_RADIO_AUTO                  1701
#define IDC_BTN_PHOTO                   1703
#define IDC_RADIO_MENTION               1704
#define IDC_EDIT_PASS3                  1706
#define IDC_RADIO_ENTER                 1707
#define IDC_EDIT_MOBILE                 1708
#define IDC_RADIO_CTRL_ENTER            1709
#define IDC_BTN_CLOSE                   1710
#define IDC_RADIO_ANY                   1711
#define IDC_EDIT_AGE                    1712
#define IDC_CHECK_EXIT                  1713
#define IDC_CHECK_LOG                   1714
#define IDC_CHECK_SNAPSHOT              1715
#define IDC_CHECK_TEMP                  1716
#define IDC_CHECK_SYNC                  1717
#define IDC_EDIT_MSGLOG                 1718
#define IDC_CHECK_AUTORUN               1719
#define IDC_STATIC_LOGO                 1720
#define IDC_EDIT_HISTORY_PIC            1721
#define IDC_EDIT_HISTORY_FILE           1722
#define IDC_STATIC_FRIENDGROUP          1723
#define IDC_STATIC_FRIEND               1724
#define IDC_STATIC_MSGINFO              1725
#define IDC_STATIC_BTN_BAR              1727
#define IDC_STATIC_REGISTER             1728
#define IDC_STATIC_ForgetPSW            1729
#define IDC_BUTTON_VOICE                1731
#define IDC_BUTTON_VIDEO_VOICE          1731
#define IDC_BUTTON                      1732
#define IDC_BUTTON_VIDEO_SOUND          1732
#define IDC_BUTTON_FASTWORD             1733
#define IDC_BUTTON_HANGUP               1734
#define IDC_EDIT_SESSION_NUM            1735
#define IDC_STATIC_TALK_TOOLBAR         1737
#define IDC_EDIT_NOTICE                 1738
#define IDC_BTN_FACE                    1739
#define IDC_BTN_PIC                     1740
#define IDC_STATIC_TAB                  1740
#define ID_SENDMSG                      1741
#define ID_SEND                         1741
#define IDC_STATIC_SEL                  1742
#define IDC_STATIC_PREVIEW              1743
#define IDC_STATIC_VOICE                1744
#define IDC_BTN_RECEIVE_MSG_VOICE       1745
#define IDC_BTN_FRIEND_ONLINE_VOICE     1746
#define IDC_BTN_SYS_MSG_VOICE           1747
#define IDC_BTN_SHOCK_SCREEN_VOICE      1748
#define IDC_CHECK_RECEIVE_MSG_VOICE     1749
#define IDC_BTN_RECEIVE_MSG_BROWSE      1750
#define IDC_BTN_FRIEND_ONLINE_BROWSE    1751
#define IDC_BTN_SYS_MSG_BROWSE          1752
#define IDC_BTN_SHOCK_SCREEN_BROWSE     1753
#define IDC_EDIT_RECEIVE_MSG_VOICE      1754
#define IDC_EDIT_FRIEND_ONLINE_VOICE    1755
#define IDC_STATIC_NAME_VALUE           1755
#define IDC_EDIT_SYS_MSG_VOICE          1756
#define IDC_STATIC_SEX_VALUE            1756
#define IDC_EDIT_SHOCK_SCREEN_VOICE     1757
#define IDC_STATIC_LOCAL_VALUE          1757
#define IDC_STATIC_BIRTHDAY             1758
#define IDC_STATIC_MOBILE_VALUE         1759
#define IDC_STATIC_TEL_VALUE            1760
#define IDC_STATIC_EMAIL_VALUE          1761
#define IDC_STATIC_INDUSTRY_VALUE       1762
#define IDC_BTN_EDIT                    1763
#define IDC_RADIO_PUBLIC_TO_FRIEND      1764
#define IDC_BTN_SENDMSG                 1765
#define IDC_BTN_ENTERSHOP               1766
#define IDC_EDIT_                       1766
#define IDC_EDIT_REMARK                 1766
#define IDC_RADIO_HIGH                  1767
#define ID_OK                           1768
#define IDC_STATIC_GUIDE                1769
#define IDC_STATIC_GUIDE2               1770
#define IDC_STATIC_CLOSE_TAB            1770
#define IDC_STATIC_MSG_RANGE            1771
#define IDC_                            1771
#define IDC_BTN_INSTALL                 1771
#define IDC_COMBO3                      1772
#define IDC_COMBO_DATE_DAY              1772
#define IDC_COMBO_DATE_YEAR             1773
#define IDC_COMBO_DATE_MONTH            1774
#define IDC_STATIC_NAME_REQUIRED        1775
#define IDC_STATIC_KINDS_REQUIRED       1776
#define IDC_STATIC_CAREER               1777
#define IDC_STATIC_                     1778
#define IDC_STATIC_LEVEL_TEXT           1779
#define IDC_STATIC_LOGIN                1780
#define IDC_STATIC_MAINFORM             1781
#define IDC_STATIC_MSG_SETTTING         1782
#define IDC_STATIC_MSG_SEND_TYPE        1783
#define IDC_STATIC_SHORTCUT_KEY         1784
#define IDC_STATIC_VOICESETTING         1785
#define IDC_STATIC_VIDEO                1787
#define IDC_COMBO_VOICE_INPUT           1788
#define IDC_STATIC_FILE_MANAGE          1789
#define IDC_CHECK_CLUSTER               1790
#define IDC_CHECK_CLEAR_MSG             1791
#define IDC_STATIC_FILE_SEL             1792
#define IDC_BTN_RECTANGLE               1793
#define IDC_BTN_ELLIPSE                 1794
#define IDC_STATIC_SOFT_UPDATE          1795
#define IDC_STATIC_PWD                  1796
#define IDC_STATIC_VERIFY_SETTING       1797
#define IDC_STATIC_MSG_LOG              1798
#define IDC_STATIC_FILE_TRAN            1799
#define IDC_EDIT                        1800
#define IDC_BTN_SMALL                   1801
#define IDC_BTN_NORMAL                  1802
#define IDC_BTN_BIG                     1803
#define IDC_STATIC_COLOR                1804
#define IDC_BTN_REVOKE                  1805
#define IDC_BTN_CUSTSER_TRAN            1806
#define IDC_BTN_SELECTPIC               1807
#define IDC_STATIC_PICEXT               1808
#define ID_MENU_EXIT                    30000
#define ID_FONTNAME                     30001
#define ID_FONTSIZE                     30002
#define ID_UNDERLINE                    30003
#define ID_ITALIC                       30004
#define ID_MENU_ABORT                   30005
#define ID_BOLD                         30006
#define ID_COLOR                        30007
#define ID_EMOTION                      30008
#define ID_INVITE                       30009
#define ID_MENU_CHECKVERSION            30010
#define ID_MENU_HELP                    30011
#define ID_MENU_ABOUT                   30012
#define ID_MENU_MODI                    30013
#define ID_MENU_REGISTER                30014
#define ID_MENU_AUTOCLEAR               30015
#define ID_BUTTON32790                  30016
#define ID_BUTTON32791                  30017
#define ID_BUTTON32792                  30018
#define ID_BUTTON32793                  30019
#define ID_BUTTON32794                  30020
#define ID_BUTTON32795                  30021
#define ID_MENU_CHANGEUSER              30022
#define ID_BLG_FONTSIZE                 30023
#define ID_BLG_IMAGE                    30024
#define ID_BLG_EMOTION                  30025
#define ID_FORDELETE                    30026
#define ID_MENU_HIDE                    30027
#define ID_MENU_OFFLINE                 30028
#define ID_MENU_CONFIG                  30029
#define ID_Menu                         30030
#define ID_Menu32815                    30031
#define ID_MENU_REGISTER_P2P            30032
#define ID_TEST                         30033
#define ID_BLG_BOLD                     30034
#define ID_BLG_FONTNAME                 30035
#define ID_MENU_NEWMAG                  30036
#define ID_BLG_ITALIC                   30037
#define ID_BLG_UNDERLINE                30038
#define ID_FORMAT_ALIGN_CENTER          30039
#define ID_MENU_SYSCONFIG               30040
#define ID_FORMAT_ALIGN_LEFT            30041
#define ID_FORMAT_ALIGN_RIGHT           30042
#define ID_ROOT_32829                   30043
#define ID_WEBFACE                      30044
#define ID_BLG_BULLETS                  30045
#define ID_LINK                         30046
#define ID_HELP_SHOW                    30047
#define ID_MENU_ONLINE                  30048
#define ID_MENU_LEAVE                   30049
#define ID_BLG_NUMBER                   30050
#define ID_HELP_CONTENT                 30051
#define ID_ROOT_32836                   30052
#define ID_SUBSCRIBE_MENU               30053
#define ID_ACC_IP                       30054
#define ID_ACCELERATOR32840             30055
#define ID_MY_HOME                      30056
#define ID_MY_PIC                       30057
#define ID_MY_ARTICLE                   30058
#define ID_WRITE_ARTICLE                30059
#define ID_UP_PIC                       30060
#define ID_BIG_HEAD                     30061
#define ID_FRIEND_ARTICLE               30062
#define ID_FRIEND_PIC                   30063
#define ID_BLG_COLORMENU                30064
#define ID_MAIL_INVITE                  30065
#define ID_ROOT_32853                   30066
#define ID_ROOT_32861                   30067
#define ID_32862                        30068
#define ID_32863                        30069
#define ID_32864                        30070
#define ID_MENU_HOME                    30071
#define ID_MENU_SEARCH_FRIEND           30072
#define ID_MENU_MAIL_INVITE             30073
#define ID_MENU_CREATE_FAMILY           30074
#define ID_MENU_SEARCH_FAMILY           30075
#define ID_MENU_UPLOAD_PIC              30076
#define ID_MENU_MY_PICTURE              30077
#define ID_MENU_PICTURE_HOME            30078
#define ID_MENU_CHANGE_HEAD             30079
#define ID_MENU_BIGHEAD                 30080
#define ID_MENU_SERVER                  30081
#define ID_MENU_WRITE_ARTICLE           30082
#define ID_MENU_MY_ARTICLE              30083
#define ID_MENU_ARTICLE_HOME            30084
#define ID_ROOT_32892                   30085
#define ID_MENU_MEDIA                   30086
#define ID_ROOT_XXX                     30087
#define ID_ROOT_32898                   30088
#define ID_ROOT_32899                   30089
#define ID_ROOT_32900                   30090
#define ID_STATUS_ONLINE                30091
#define ID_STATUS                       30092
#define ID_STATUS_BUSY                  30093
#define ID_SATUS_OFFLINE                30094
#define ID_STATUS_HIDE                  30095
#define ID_SATUS_LEAVE                  30096
#define ID_MENU_VIEW_CLUSTERINFO        30097
#define ID_Menu32908                    30098
#define ID_MENU_CLUSTER_EXIT            30099
#define ID_Menu_B                       30100
#define ID_MENU_CLUSTER_LOG             30101
#define ID_MENU_BUSY                    30102
#define ID_MENU_CLUSTER_PROFILE         30103
#define ID_MENU_VIEW_CLUSTER_INFO       30104
#define ID_MENU_REC_NOTICE              30105
#define ID_MENU_REC_ONLY                30106
#define ID_MENU_UNREAD_SHOW             30107
#define ID_MENU_REJECT_MSG              30108
#define ID_MENU_SPEC_USER               30109
#define ID_MENU_CHANGE_USER             30110
#define ID_MENU_MOD_PSW                 30111
#define ID_ROOT_32923                   30112
#define ID_Menu32924                    30113
#define ID_Menu32927                    30116
#define IDC_TEXT_ID                     30117
#define ID_Menu30118                    30118
#define ID_ROOT_30119                   30119
#define ID_MENU_UPDATE                  30120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        362
#define _APS_NEXT_COMMAND_VALUE         30122
#define _APS_NEXT_CONTROL_VALUE         1809
#define _APS_NEXT_SYMED_VALUE           503
#endif
#endif
