/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : te
Source Server Version : 110200
Source Host           : 10.211.64.108:1521
Source Schema         : IM

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-08-06 09:32:35
*/


-- ----------------------------
-- Table structure for T_SESSION_DETAIL
-- ----------------------------
CREATE global temporary table  "IM"."T_SESSION_DETAIL" (
"I_FROMID" NUMBER(20) NOT NULL ,
"I_TOID" NUMBER(20) NOT NULL ,
"I_LOGINTIME" NUMBER(20) NOT NULL ,
"I_ASKTIME" NUMBER(20) NULL ,
"I_REPLYTIME" NUMBER(20) NULL ,
"I_DUR" NUMBER(20) NULL ,
"I_MESSAGE_COUNT" NUMBER(20) NULL ,
"I_START_TIME" NUMBER(20) NULL ,
"I_END_TIME" NUMBER(20) NULL ,
"I_SESSION_LEN" NUMBER(20) NULL ,
"I_REPLY_START" NUMBER(20) NULL ,
"I_REPLY_END" NUMBER(20) NULL ,
"I_REPLY_LEN" NUMBER(20) NULL 
)
On Commit Delete Rows ;

-- ----------------------------
-- Checks structure for table T_SESSION_DETAIL
-- ----------------------------
ALTER TABLE "IM"."T_SESSION_DETAIL" ADD CHECK ("I_FROMID" IS NOT NULL);
ALTER TABLE "IM"."T_SESSION_DETAIL" ADD CHECK ("I_TOID" IS NOT NULL);
ALTER TABLE "IM"."T_SESSION_DETAIL" ADD CHECK ("I_LOGINTIME" IS NOT NULL);


COMMENT ON TABLE "IM"."T_SESSION_DETAIL" IS '回复明细表:临时表，用于存放统计出来的会话的数据';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_FROMID" IS '会话中商家的ID';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_TOID" IS '会话中买家的ID';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_LOGINTIME" IS '会话标示';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_ASKTIME" IS '买家发送的第一条消息的时间';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_REPLYTIME" IS '卖家发送的第一条消息的时间';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_DUR" IS '卖家回复买家中间的时间差';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_MESSAGE_COUNT" IS '会话中卖家一共回复的消息数';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_START_TIME" IS '会话开始的时间';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_END_TIME" IS '会话结束的时间';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_SESSION_LEN" IS '会话的时长';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_REPLY_START" IS '商家一次回复的时间';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_REPLY_END" IS '商家最后一次回复的时间';
COMMENT ON COLUMN "IM"."T_SESSION_DETAIL"."I_REPLY_LEN" IS '商家第一次回复到最后一次回复的时间差';


/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : te
Source Server Version : 110200
Source Host           : 10.211.64.108:1521
Source Schema         : IM

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-08-06 09:32:08
*/


-- ----------------------------
-- Table structure for IM_SUBMERCHANT_ATTENDANCE
-- ----------------------------
CREATE TABLE "IM"."IM_SUBMERCHANT_ATTENDANCE" (
"I_SUBMERCHANT_ID" NUMBER(15) NOT NULL ,
"I_MERCHANT_ID" NUMBER(12) NOT NULL ,
"I_STATISTICS_TIME" NUMBER(11) NOT NULL ,
"I_LOGIN_COUNT" NUMBER(3) DEFAULT 0  NULL ,
"I_FIRST_ONLINE_TIME" NUMBER(11) NULL ,
"I_LAST_ONLINE_TIME" NUMBER(11) NULL ,
"I_TOTAL_ONLINE_DURATION" NUMBER(6) DEFAULT 0  NULL ,
"I_TOTAL_HANGING_DURATION" NUMBER(6) DEFAULT 0  NULL ,
"I_TOTAL_OFFLINE_DURATION" NUMBER(6) DEFAULT 0  NULL ,
"UPDATE_TIME" TIMESTAMP(6)  DEFAULT systimestamp  NOT NULL 
)
TABLESPACE ecsdata;

-- ----------------------------
-- Indexes structure for table IM_SUBMERCHANT_ATTENDANCE
-- ----------------------------
CREATE INDEX "IM"."ATTENDACNCE_STATISTICS_TIME"
ON "IM"."IM_SUBMERCHANT_ATTENDANCE" ("I_STATISTICS_TIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table IM_SUBMERCHANT_ATTENDANCE
-- ----------------------------
ALTER TABLE "IM"."IM_SUBMERCHANT_ATTENDANCE" ADD CHECK ("I_SUBMERCHANT_ID" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_ATTENDANCE" ADD CHECK ("I_MERCHANT_ID" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_ATTENDANCE" ADD CHECK ("I_STATISTICS_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IM_SUBMERCHANT_ATTENDANCE
-- ----------------------------
ALTER TABLE "IM"."IM_SUBMERCHANT_ATTENDANCE" ADD PRIMARY KEY ("I_SUBMERCHANT_ID", "I_MERCHANT_ID", "I_STATISTICS_TIME");



COMMENT ON TABLE "IM"."IM_SUBMERCHANT_ATTENDANCE" IS '出勤率统计';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_SUBMERCHANT_ID" IS '子账号的ID';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_MERCHANT_ID" IS '商家的ID';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_STATISTICS_TIME" IS '统计时间：当天的0点0分0秒';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_LOGIN_COUNT" IS '子账号当天登陆的次数';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_FIRST_ONLINE_TIME" IS '子账号当天第一次登陆的时间';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_LAST_ONLINE_TIME" IS '子账号当天最后一次登陆的时间';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_TOTAL_ONLINE_DURATION" IS '子账号当天在线的总时长';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_TOTAL_HANGING_DURATION" IS '子账号当天挂起的总时长';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_ATTENDANCE"."I_TOTAL_OFFLINE_DURATION" IS '子账号当天离线的总时长';


/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : te
Source Server Version : 110200
Source Host           : 10.211.64.108:1521
Source Schema         : IM

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-08-06 09:31:58
*/


-- ----------------------------
-- Table structure for IM_SUBMERCHANT_WORKLOAD
-- ----------------------------
CREATE TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" (
"I_SUBMERCHANT_ID" NUMBER(10) NOT NULL ,
"I_MERCHANT_ID" NUMBER(10) NOT NULL ,
"I_STATISTICS_TIME" NUMBER(20) NOT NULL ,
"I_RESPONSE_DURATION" NUMBER(10) NOT NULL ,
"I_SESSION_DURATION" NUMBER(10) NOT NULL ,
"I_SESSION_COUNT" NUMBER(10) NOT NULL ,
"I_RESPONSE_MESSAGE_COUNT" NUMBER(10) NOT NULL ,
"I_RECEPTION_DURATION" NUMBER(10) NOT NULL ,
"V_RESPONSE_IDS" CLOB NULL ,
"V_ASKING_IDS" CLOB NULL ,
"I_RESPONSE_COUNT" NUMBER(10) NOT NULL ,
"I_RESPONSE_IN_90S_COUNT" NUMBER(10) NOT NULL ,
"UPDATE_TIME" TIMESTAMP(6)  DEFAULT systimestamp  NOT NULL 
)
TABLESPACE ecsdata;
-- ----------------------------
-- Indexes structure for table IM_SUBMERCHANT_WORKLOAD
-- ----------------------------
CREATE INDEX "IM"."WORKLOAD_STATISTICS_TIME"
ON "IM"."IM_SUBMERCHANT_WORKLOAD" ("I_STATISTICS_TIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table IM_SUBMERCHANT_WORKLOAD
-- ----------------------------
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_SUBMERCHANT_ID" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_MERCHANT_ID" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_STATISTICS_TIME" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RESPONSE_DURATION" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_SESSION_DURATION" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_SESSION_COUNT" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RESPONSE_MESSAGE_COUNT" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RECEPTION_DURATION" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RESPONSE_COUNT" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_SUBMERCHANT_ID" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_MERCHANT_ID" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_STATISTICS_TIME" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RESPONSE_DURATION" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_SESSION_DURATION" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_SESSION_COUNT" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RESPONSE_MESSAGE_COUNT" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RECEPTION_DURATION" IS NOT NULL);
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD CHECK ("I_RESPONSE_COUNT" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IM_SUBMERCHANT_WORKLOAD
-- ----------------------------
ALTER TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" ADD PRIMARY KEY ("I_SUBMERCHANT_ID", "I_STATISTICS_TIME");



COMMENT ON TABLE "IM"."IM_SUBMERCHANT_WORKLOAD" IS '工作量统计';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_SUBMERCHANT_ID" IS '子账号的ID';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_MERCHANT_ID" IS '商家的ID';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_STATISTICS_TIME" IS '统计时间：当天的0点0分0秒';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_RESPONSE_DURATION" IS '子账号响应客户的时间总和';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_SESSION_DURATION" IS '子账号所有会话的时间总和';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_SESSION_COUNT" IS '子账号所有会话的个数';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_RESPONSE_MESSAGE_COUNT" IS '子账号所有回复的消息条数';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_RECEPTION_DURATION" IS '子账号接待总时长';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."V_RESPONSE_IDS" IS '子账号回复过的所有客户的ID';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."V_ASKING_IDS" IS '所有咨询过该子账号的客户的ID';
COMMENT ON COLUMN "IM"."IM_SUBMERCHANT_WORKLOAD"."I_RESPONSE_COUNT" IS '子账号回复过的次数';