/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : wh-oracle01.fn.com_1521_ORCL
Source Server Version : 110200
Source Host           : wh-oracle01.fn.com:1521
Source Schema         : IM

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2016-04-22 09:57:50
*/


-- ----------------------------
-- Table structure for T_TOUCH_PORTAL_BOARD_CONFIG
-- ----------------------------
CREATE TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" (
"I_ID" NUMBER(10) NOT NULL ,
"V_TITLE" VARCHAR2(60 BYTE) NOT NULL ,
"V_DESCRIPTION" VARCHAR2(120 BYTE) NOT NULL ,
"V_ICON" VARCHAR2(300 BYTE) NOT NULL ,
"I_SHOW_ORDER" NUMBER(4) NOT NULL ,
"C_IS_BIND_GROUP" CHAR(1 BYTE) NOT NULL ,
"I_GROUP_ID" NUMBER(10) NULL ,
"C_IS_BIND_USER_ORDER" CHAR(1 BYTE) NOT NULL ,
"C_DATA_TYPE" CHAR(1 BYTE) NOT NULL ,
"UPDATE_TIME" TIMESTAMP(6)  DEFAULT systimestamp  NULL 
)
TABLESPACE ecsdata;

COMMENT ON TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" IS '触屏portal页板块表配置';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."I_ID" IS '主键，自增';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."V_TITLE" IS '版块名称';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."V_DESCRIPTION" IS '版块描述';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."V_ICON" IS '版块图标';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."I_SHOW_ORDER" IS '显示顺序';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."C_IS_BIND_GROUP" IS '是否绑定客服分组';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."I_GROUP_ID" IS '客服分组id';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."C_IS_BIND_USER_ORDER" IS '是否绑定订单';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."C_DATA_TYPE" IS '版块所属类型：设计时、运行时';
COMMENT ON COLUMN "IM"."T_TOUCH_PORTAL_BOARD_CONFIG"."UPDATE_TIME" IS '最后更新时间';

-- ----------------------------
-- Indexes structure for table T_TOUCH_PORTAL_BOARD_CONFIG
-- ----------------------------

-- ----------------------------
-- Checks structure for table T_TOUCH_PORTAL_BOARD_CONFIG
-- ----------------------------
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("I_ID" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("V_TITLE" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("V_DESCRIPTION" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("V_ICON" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("I_SHOW_ORDER" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("C_IS_BIND_GROUP" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("C_IS_BIND_USER_ORDER" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("C_DATA_TYPE" IS NOT NULL);
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("C_DATA_TYPE" IN ('0', '1'));
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("C_IS_BIND_GROUP" IN ('0', '1'));
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD CHECK ("C_IS_BIND_USER_ORDER" IN ('0', '1'));

-- ----------------------------
-- Primary Key structure for table T_TOUCH_PORTAL_BOARD_CONFIG
-- ----------------------------
ALTER TABLE "IM"."T_TOUCH_PORTAL_BOARD_CONFIG" ADD PRIMARY KEY ("I_ID");

CREATE SEQUENCE "IM"."SEQ_TOUCH_PORTAL_BOARD_CONFIG" MINVALUE 1 MAXVALUE 1000000 INCREMENT BY 1 NOCYCLE;
