//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WriteArticle.rc
//
#define IDS_PROJNAME                    100
#define IDR_WRITEARTICLE                101
#define IDR_WRITEARTICLEX               103
#define IDR_ARTICLEDATAX                104
#define IDD_IMAGEPREVIEWDLG             182
#define IDD_MAINFRAME                   201
#define IDC_BUTTONF                     201
#define IDC_BTN_CREATEDIR               201
#define IDC_STATIC_OPEN1                202
#define IDR_MENU1                       202
#define IDC_BUTTON_OPEN                 202
#define IDC_STATIC_OPENF                202
#define IDC_BUTTON_WEBARTS              203
#define IDC_BTN_DEL1                    203
#define IDC_BUTTONS                     204
#define IDC_BTN_DEL2                    204
#define IDR_MENU_TEMPLATE               205
#define IDR_TOOLBAR_BLOG                205
#define IDR_TOOLBAR1                    206
#define IDC_BUTTONT                     206
#define IDC_BTN_DEL3                    206
#define IDC_BUTTON_OPEN5                206
#define IDC_STATIC_PARTICLE3            207
#define IDR_MENU2                       208
#define IDC_BUTTON_REFRESH              208
#define IDR_MENU3                       209
#define IDC_ICON_LINK                   209
#define IDR_MENU4                       210
#define IDC_BUTTON_TOP                  210
#define IDC_ICON_LOCAL                  210
#define IDC_BUTTON_POST1                211
#define IDC_ICON_WEB                    211
#define IDC_STATIC_ATRS                 212
#define IDC_BUTTON_MYARTICLE            212
#define IDC_STATIC_PIC                  212
#define IDC_ICON_WOKU                   213
#define IDC_BUTTON_WEBP                 214
#define IDR_TOOL_BUTTONS                215
#define IDC_STATIC_ARTS                 215
#define IDC_STATIC_SPACE                215
#define IDC_STATIC_WEBARTS              216
#define IDR_TOOL_SET                    217
#define IDC_BUTTON1_OPEN                218
#define IDC_STATIC_MORE                 220
#define IDB_BITMAP_DEL                  220
#define IDR_MENU5                       221
#define IDC_STATIC_PARTICLE2            221
#define IDD_DIALOG_OPEN                 222
#define IDC_STATIC_MOREPARTS            222
#define IDC_COMBO1                      225
#define IDC_BUTTON_OK                   228
#define IDC_BUTTON_CANCLE               229
#define IDC_BUTTON_PCANCLE              229
#define IDB_BITMAP_WOKU                 229
#define IDC_BUTTON_DEL                  230
#define IDC_STATIC_TAG                  231
#define IDB_BITMAP_LINK                 231
#define IDC_STATIC_APPARTS              232
#define IDB_BITMAP_PIC                  232
#define IDC_STATIC_VIEWTYPE             233
#define IDB_BITMAP_WEBPIC               233
#define IDC_STATIC_PARTS1               234
#define IDC_OK                          235
#define IDC_CANCEL                      236
#define IDB_BITMAP_NEW                  236
#define IDC_STATIC_POSTOPEN             237
#define IDC_STATIC_POSTARTS             238
#define IDC_COMBO_ARTCOUNT              239
#define IDB_BITMAP3                     239
#define IDC_BUTTON_CANCLEP              240
#define IDB_BITMAP_OPEN                 243
#define IDC_LIST1                       245
#define IDC_STATIC_MYSPACE              246
#define IDC_STATIC_VIEWSPACE            247
#define IDC_STATIC_WOKU                 248
#define IDI_ICON_ARTS                   248
#define IDI_ICON_LOCALARTS              248
#define IDI_ICON_WEBARTS                249
#define IDD_DIALOG_PROGRESS             353
#define IDD_WRITE_BLOG_PANEL            421
#define IDD_DIALOG_TEST_WEBPIC          432
#define IDC_STATIC_LOCAL1               598
#define IDC_STATIC_LOCAL2               599
#define IDC_STATIC_LOCAL3               600
#define IDC_STATIC_LINK                 601
#define IDC_STATIC_WEB                  602
#define IDC_STATIC_LOCALFILE            603
#define IDC_BUTTON_INSERTWEB            604
#define IDC_BUTTON_INSERTWOKU           605
#define IDC_BUTTON_INSERTLINK           606
#define IDC_BUTTON_INSERTLOCAL          607
#define IDC_EDIT1                       1000
#define IDC_EDIT_TITLE                  1000
#define IDC_IMAGEPREVIEW                1009
#define IDC_STATIC_LINE                 1009
#define IDC_PREVIEWNAME                 1013
#define IDC_FILESIZE                    1014
#define IDC_EXPLORER1                   1014
#define IDC_BUTTON_I                    1020
#define IDC_BUTTON_B                    1021
#define IDC_EDIT_NAME                   1026
#define IDC_STATIC1                     1034
#define IDC_STATIC2                     1035
#define IDC_STATIC3                     1037
#define IDC_DATE_BEGIN                  1060
#define IDC_DATE_END                    1061
#define IDC_BUTTON_LOCALFILE            1070
#define IDC_BUTTON_RIGHT                1070
#define IDC_BUTTON_WEBPIC               1071
#define IDC_BUTTON_139PIC               1072
#define IDC_DHTMLEDIT_BLOG              1082
#define IDC_BUTTON_C                    1085
#define IDC_BUTTON_U                    1086
#define IDC_COMBO_DIR                   1089
#define IDC_COMBO_VIEW                  1091
#define IDC_BUTTON_POST                 1094
#define IDC_BUTTON_RESET                1095
#define IDC_BUTTON_SAVE                 1096
#define IDC_STATIC_HIDE                 1105
#define IDC_COMBO_FONTNAME              1107
#define IDC_COMBO_FONTSIZE              1108
#define IDC_STATIC_TIP1                 1146
#define IDD_DIALOG_WRITEBLOG            1148
#define IDC_STATIC_PROGRESS             1151
#define IDC_STATIC_LINK2                1156
#define IDC_STATIC_LINK3                1157
#define IDD_DIALOG_PROGRESS2            1159
#define IDD_DIALOG_PROGRESS3            1160
#define IDD_DIALOG_WEBFACE              1167
#define IDD_DIALOG_WEBPIC               1168
#define IDD_DIALOG_CREATEDIR            1175
#define IDC_BUTTON_LEFT                 1188
#define IDC_SLIDER1                     1190
#define IDC_COMBO_TAG                   1192
#define IDC_CHECK_TOP                   1193
#define IDC_STATIC_ETCHED2              1194
#define IDC_STATIC_ETCHED1              1195
#define IDC_BUTTON_ARTICLE              1196
#define IDC_BUTTON_ARTICLE2             1197
#define IDC_STATIC_PARTICLE1            1203
#define IDC_EDIT_PATH                   1208
#define IDC_BUTTON_PATH                 1209
#define IDTEST                          1221
#define IDC_EDIT_URL                    1222
#define IDC_STATIC_CREATE               1243
#define IDC_EDIT_DIR                    1244
#define IDC_LIST_DIR                    1245
#define ID_CUT                          32768
#define ID_FORDELETE                    32769
#define ID_COPY                         32769
#define ID_PASTE                        32770
#define ID_SELALL                       32771
#define ID_REDO                         32774
#define ID_UNDO                         32775
#define ID_RELOAD                       32777
#define ID_POST                         32779
#define ID_WOKU_PIC                     32781
#define ID_Menu                         32782
#define ID_BLG_FONTSIZE                 32798
#define ID_BUTTON_NEW                   32810
#define ID_BUTTON_OPEN                  32811
#define ID_BUTTON_SAVE                  32812
#define ID_BUTTON_POST                  32813
#define ID_TOOL_SET1                    32814
#define ID_NEW_ARTICLES                 32816
#define ID_BLG_BOLD                     32821
#define ID_BLG_FONTNAME                 32822
#define ID_BLG_ITALIC                   32825
#define ID_BLG_UNDERLINE                32826
#define ID_FORMAT_ALIGN_CENTER          32827
#define ID_FORMAT_ALIGN_LEFT            32828
#define ID_FORMAT_ALIGN_RIGHT           32829
#define ID_WEBFACE                      32830
#define ID_BLG_BULLETS                  32831
#define ID_LINK                         32832
#define ID_EXIT                         32833
#define ID_BLG_NUMBER                   32834
#define ID_NEW_ARTICLE                  32835
#define ID_LOCAL_PIC                    32840
#define ID_HYPERLINK                    32841
#define ID_WEB_PIC                      32842
#define ID_VIEW_MYARTICLES              32843
#define ID_VIEW_WEBARTICLES             32844
#define ID_BLG_COLORMENU                32849
#define ID_OPEN                         32931
#define ID_SAVE_ARTICLE                 32932

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         213
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
