//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HmgUploadPicture.rc
//
#define IDB_UPLOADPICTUREX              1
#define IDS_PROJNAME                    100
#define IDR_HMGUPLOADPICTURE            101
#define IDD_DLG_OPERATIONS              101
#define IDR_HMGUPLOADPICTUREX           103
#define IDB_MAX_DOWN                    113
#define IDB_CLOSE_DOWN                  114
#define IDB_MIN_DOWN                    115
#define IDB_RESTORE_DOWN                116
#define IDB_DLG_CAPTION_R               117
#define IDB_DLG_CAPTION_L               118
#define IDB_DLG_CAPTION_M               119
#define IDB_IM_BTN_DISABLE              120
#define IDB_COLUMN_BTN_TOP_NORMAL       123
#define IDB_COLUMN_BTN_BOTTOM_NORMAL    124
#define IDB_COLUMN_BTN_MID_NORMAL       125
#define IDB_COLUMN_BTN_ARROW_LEFT       126
#define IDB_COLUMN_BTN_ARROW_RIGHT      127
#define IDI_SEL_PIC                     131
#define IDB_IM_COMBO_BUTTON             452
#define IDB_CLOSE_NORMAL                152
#define IDB_CLOSE_HOT                   153
#define IDB_MAX_HOT                     154
#define IDB_MAX_NORMAL                  155
#define IDB_MIN_HOT                     156
#define IDB_MIN_NORMAL                  157
#define IDB_RESTORE_HOT                 158
#define IDB_RESTORE_NORMAL              159
#define IDD_PROPPAGE_UPLOADPICTUREX     200
#define IDC_DLG_UPLOAD_STATIC_GROUP1    201
#define IDI_MAIN                        201
#define IDB_BITMAP_RIGHT2               202
#define IDB_BITMAP_RIGHT                203
#define IDB_BITMAP_LEFT                 204
#define IDB_DRAGDROP_SINGLE             205
#define IDB_DRAGDROP_MULTI              206
#define IDB_BITMAP_BIG2                 207
#define IDC_NODRAG                      208
#define IDB_DLG_CAPTION_BAR             209
#define IDC_HANDLE                      209
#define IDB_PROGRESSBAR_GREEN           210
#define IDB_PROGRESSBAR_RED             211
#define IDC_DLG_UPLOAD_STATIC_PROMPT1   212
#define IDB_PROGRESSBAR_BLUE            212
#define IDC_DLG_UPLOAD_STATIC_PROMPT2   213
#define IDC_DLG_UPLOAD_STATIC_PROMPT3   214
#define IDB_BITMAP_HINT                 214
#define IDC_DLG_UPLOAD_STATIC_PROMPT4   215
#define IDR_MAINFRAME                   215
#define IDC_DLG_UPLOAD_TAG_COMBO        217
#define IDC_DLG_UPLOAD_ALBUM_COMBO      218
#define IDB_PROGRESSBAR_V2_GRAY         218
#define IDC_DLG_UPLOAD_ALBUM            219
#define IDB_PROGRESSBAR_V2_BLUE         219
#define IDC_DLG_UPLOAD_ACL              220
#define IDB_PROGRESSBAR_V2_GREEN        220
#define IDC_DLG_UPLOAD_IMAGE_SIZE       221
#define IDB_PROGRESSBAR_V2_RIGHTLINE    221
#define IDC_DLG_UPLOAD_STATIC_GROUP2    222
#define IDB_PROGRESSBAR_V2_LEFTLINE     222
#define IDC_DLG_UPLOAD_BTN_RESETINFO    223
#define IDD_DLG_PANEL1                  223
#define IDC_DLG_UPLOAD_BTN_STARTSEND    224
#define IDD_DLG_PANEL2                  224
#define IDD_DLG_UPLOADING               225
#define IDC_DLG_UPLOAD_STATIC_HYPERLINK 225
#define IDC_DLG_UPLOAD_STATIC_GROUP3    226
#define IDD_DLG_UPLOADPICSHELLEXT       226
#define IDC_DLG_UPLOAD_STATIC_REMAINSIZE_1 227
#define IDB_HELP_NORMAL                 227
#define IDC_DLG_UPLOAD_PROGRESSCTRL     228
#define IDB_HELP_DOWN                   228
#define IDC_DLG_UPLOAD_STATIC_REMAINSIZE_2 229
#define IDB_HELP_HOT                    229
#define IDC_STATIC_TREECTRL_PROMT       231
#define IDC_DLG_UPLOAD_STATIC_INFO      233
#define IDC_STATIC_LISTCTRL_PROMPT      234
#define IDC_DLG_UPLOADING_PROGRESSCTRL  236
#define IDC_DLG_UPLOADING_STATIC_PROMPT01 237
#define IDC_DLG_UPLOADING_STATIC_PROMP02 238
#define IDB_BTN1_DOWN                   238
#define IDB_BTN1_DISABLE                239
#define IDC_DLG_UPLOADING_CANCEL        240
#define IDB_BTN1_HOT                    240
#define IDC_DLG_UPLOADING_STATIC_CANCEL 241
#define IDB_BTN1_NORMAL                 241
#define IDB_IM_BTN_NORMAL               259
#define IDB_IM_BTN_HOVER                260
#define IDR_GIF_LOGIN                   282
#define IDB_BTN_ITALIC_NORMAL           289
#define IDB_IM_SCROLLBAR                376
#define IDB_IM_BTN_DOWN                 336
#define IDD_DIALOG_PROGRESS             353
#define IDB_MAINICON                    377
#define IDB_BITMAP_BIG                  390
#define IDB_BITMAP_LEFT2                391
#define IDI_UPD_PIC                     391
#define IDB_COLUMN_BTN_TOP_HOT          415
#define IDB_COLUMN_BTN_MID_HOT          416
#define IDB_COLUMN_BTN_BOTTOM_HOT       417
#define IDB_COLUMN_BTN_BOTTOM_DISABLE   418
#define IDB_COLUMN_BTN_TOP_DISABLE      419
#define IDB_COLUMN_BTN_MID_DISABLE      420
#define IDB_COLUMN_BTN_TOP_DOWN         421
#define IDB_COLUMN_BTN_MID_DOWN         422
#define IDB_COLUMN_BTN_BOTTOM_DOWN      423
#define IDC_ADDUPLOAD_BUTTON            1006
#define IDC_DIR_TREE                    1007
#define IDC_REMOVEUPLOADFILE_BUTTON     1008
#define IDC_FILE_LIST                   1009
#define IDC_UPLOADFILE_LIST             1010
#define IDC_ADDALLUPLOADBUTTON          1012
#define IDC_REMOVEALLUPLOADFILES_BUTTON 1013
#define IDC_DESCRIPTION_STATIC          1023
#define IDC_STATIC1                     1034
#define IDC_DLG_UPLOAD_STATIC_SELECTFILEINFO 1036
#define IDC_DLG_UPLOAD_STATIC_SELECTFILEINFO2 1037
#define IDC_CANCEL                      1114
#define IDC_STATIC_PROGRESS             1151
#define IDD_UPLOADPHOTO_DIALOG          1156
#define IDD_PREVIEW_DIALOG              1157
#define IDC_STATIC_LINE2                1159
#define IDD_DIALOG_PROGRESS2            1159
#define IDD_DIALOG_PROGRESS3            1160

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
