#!/bin/sh 
HOLD1=/tmp/imhold1.$$
HOLD2=/tmp/imhold2.$$
HOLD3=/tmp/imhold3.$$
HOLD4=/tmp/imhold4.$$
WORKINGPATH=`dirname $0`/..

while [ 1 ]
do
ulimit -c unlimited

ps -A| grep ImServer | grep -v grep | awk '{print $2}' > $HOLD1
if [ ! -s $HOLD1 ]; then
	echo `date` >> ../Log/ImMonitor.log
 	echo "ImServer process isn't running..." >> ../Log/ImMonitor.log
	ulimit -c unlimited
	sleep 1
	nohup ../bin/ImServer &> /dev/null&
	echo "restart ImServer" >> ../Log/ImMonitor.log
	echo >> ../Log/ImMonitor.log
	
fi
		
#ps -A| grep WebMsgNotify | grep -v grep | awk '{print $2}' > $HOLD4
#if [ ! -s $HOLD4 ]; then
#	echo `date` >> ../Log/ImMonitor.log
# 	echo "WebMsgNotify process isn't running..." >> ../Log/ImMonitor.log
#	sleep 1
#	nohup ../bin/WebMsgNotify &> /dev/null&
#	echo "restart WebMsgNotify" >> ../Log/ImMonitor.log
#	echo >> ../Log/ImMonitor.log
	
#fi
#ps -A| grep -v WebMsgNotify | grep MsgNotify | grep -v grep | awk '{print $2}' > $HOLD4
#if [ ! -s $HOLD4 ]; then
#	echo `date` >> ../Log/ImMonitor.log
# 	echo "MsgNotify process isn't running..." >> ../Log/ImMonitor.log
#	sleep 1
#	nohup ../bin/MsgNotify &> /dev/null&
#	echo "restart MsgNotify" >> ../Log/ImMonitor.log
#	echo >> ../Log/ImMonitor.log
	
#fi
if [ -f core.* ];then
        DATE=`date "+%Y%m%d%k%M%S"`
        DUMPFILE=core$DATE.tar.gz
	UPLOADSERVER=`cat ../config/Config.ini | grep -A 2 "\[ShellConfig\]" | grep UploadDumpIP | awk -F "[=]" '{print $2}'`
        echo [$DATE] send dump file: $DUMPFILE to $UPLOADSERVER
	tar zcvf $DUMPFILE core.*
        curl -F "file=@$DUMPFILE" $UPLOADSERVER
        rm -rf core.*
fi
	sleep 300	
	
done
